// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: msgproto/login.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgLoginReq 1001
type MsgLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Token       string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	ShowAreaId  int32  `protobuf:"varint,3,opt,name=ShowAreaId,proto3" json:"ShowAreaId,omitempty"`
	SessionId   string `protobuf:"bytes,4,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	DistinctId  string `protobuf:"bytes,5,opt,name=DistinctId,proto3" json:"DistinctId,omitempty"`
	Os          string `protobuf:"bytes,6,opt,name=Os,proto3" json:"Os,omitempty"`
	ChanneCode  int32  `protobuf:"varint,7,opt,name=ChanneCode,proto3" json:"ChanneCode,omitempty"`  //渠道
	ChannePlat  string `protobuf:"bytes,8,opt,name=ChannePlat,proto3" json:"ChannePlat,omitempty"`   //渠道码(平台id)
	ChannelUUID string `protobuf:"bytes,9,opt,name=ChannelUUID,proto3" json:"ChannelUUID,omitempty"` //玩家渠道openid或UUID
}

func (x *MsgLoginReq) Reset() {
	*x = MsgLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginReq) ProtoMessage() {}

func (x *MsgLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginReq.ProtoReflect.Descriptor instead.
func (*MsgLoginReq) Descriptor() ([]byte, []int) {
	return file_msgproto_login_proto_rawDescGZIP(), []int{0}
}

func (x *MsgLoginReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MsgLoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MsgLoginReq) GetShowAreaId() int32 {
	if x != nil {
		return x.ShowAreaId
	}
	return 0
}

func (x *MsgLoginReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MsgLoginReq) GetDistinctId() string {
	if x != nil {
		return x.DistinctId
	}
	return ""
}

func (x *MsgLoginReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MsgLoginReq) GetChanneCode() int32 {
	if x != nil {
		return x.ChanneCode
	}
	return 0
}

func (x *MsgLoginReq) GetChannePlat() string {
	if x != nil {
		return x.ChannePlat
	}
	return ""
}

func (x *MsgLoginReq) GetChannelUUID() string {
	if x != nil {
		return x.ChannelUUID
	}
	return ""
}

// MsgLoginRes 1002
type MsgLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        ErrCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"` // 0 成功
	SessionId  string  `protobuf:"bytes,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	UserId     string  `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ServerTime int64   `protobuf:"varint,4,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
}

func (x *MsgLoginRes) Reset() {
	*x = MsgLoginRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoginRes) ProtoMessage() {}

func (x *MsgLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoginRes.ProtoReflect.Descriptor instead.
func (*MsgLoginRes) Descriptor() ([]byte, []int) {
	return file_msgproto_login_proto_rawDescGZIP(), []int{1}
}

func (x *MsgLoginRes) GetRet() ErrCode {
	if x != nil {
		return x.Ret
	}
	return ErrCode_OK
}

func (x *MsgLoginRes) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MsgLoginRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MsgLoginRes) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_msgproto_login_proto protoreflect.FileDescriptor

var file_msgproto_login_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x16, 0x6d, 0x73, 0x67,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x02, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x65, 0x61, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x44, 0x69, 0x73, 0x74, 0x69, 0x6e, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x4f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x55, 0x49, 0x44, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x55, 0x55, 0x49,
	0x44, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x12, 0x1e, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d, 0x73, 0x67,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgproto_login_proto_rawDescOnce sync.Once
	file_msgproto_login_proto_rawDescData = file_msgproto_login_proto_rawDesc
)

func file_msgproto_login_proto_rawDescGZIP() []byte {
	file_msgproto_login_proto_rawDescOnce.Do(func() {
		file_msgproto_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgproto_login_proto_rawDescData)
	})
	return file_msgproto_login_proto_rawDescData
}

var file_msgproto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msgproto_login_proto_goTypes = []interface{}{
	(*MsgLoginReq)(nil), // 0: msg.MsgLoginReq
	(*MsgLoginRes)(nil), // 1: msg.MsgLoginRes
	(ErrCode)(0),        // 2: msg.ErrCode
}
var file_msgproto_login_proto_depIdxs = []int32{
	2, // 0: msg.MsgLoginRes.Ret:type_name -> msg.ErrCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msgproto_login_proto_init() }
func file_msgproto_login_proto_init() {
	if File_msgproto_login_proto != nil {
		return
	}
	file_msgproto_errcode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgproto_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoginRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgproto_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgproto_login_proto_goTypes,
		DependencyIndexes: file_msgproto_login_proto_depIdxs,
		MessageInfos:      file_msgproto_login_proto_msgTypes,
	}.Build()
	File_msgproto_login_proto = out.File
	file_msgproto_login_proto_rawDesc = nil
	file_msgproto_login_proto_goTypes = nil
	file_msgproto_login_proto_depIdxs = nil
}
