// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: msgproto/msgdef.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	// 客户端请求响应消息
	MsgType_Null     MsgType = 0
	MsgType_Ping     MsgType = 100
	MsgType_Pong     MsgType = 101
	MsgType_GM       MsgType = 102
	MsgType_LoginReq MsgType = 1000
	MsgType_LoginRes MsgType = 1001
	// 主动推送的消息
	MsgType_LoadFinish   MsgType = 5000
	MsgType_NotifyLogout MsgType = 5001
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:    "Null",
		100:  "Ping",
		101:  "Pong",
		102:  "GM",
		1000: "LoginReq",
		1001: "LoginRes",
		5000: "LoadFinish",
		5001: "NotifyLogout",
	}
	MsgType_value = map[string]int32{
		"Null":         0,
		"Ping":         100,
		"Pong":         101,
		"GM":           102,
		"LoginReq":     1000,
		"LoginRes":     1001,
		"LoadFinish":   5000,
		"NotifyLogout": 5001,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgproto_msgdef_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_msgproto_msgdef_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_msgproto_msgdef_proto_rawDescGZIP(), []int{0}
}

var File_msgproto_msgdef_proto protoreflect.FileDescriptor

var file_msgproto_msgdef_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x64, 0x65,
	0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x71, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x6f, 0x6e, 0x67, 0x10, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x47, 0x4d, 0x10, 0x66, 0x12, 0x0d, 0x0a,
	0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x10, 0xe8, 0x07, 0x12, 0x0d, 0x0a, 0x08,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x10, 0xe9, 0x07, 0x12, 0x0f, 0x0a, 0x0a, 0x4c,
	0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x10, 0x88, 0x27, 0x12, 0x11, 0x0a, 0x0c,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0x89, 0x27, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgproto_msgdef_proto_rawDescOnce sync.Once
	file_msgproto_msgdef_proto_rawDescData = file_msgproto_msgdef_proto_rawDesc
)

func file_msgproto_msgdef_proto_rawDescGZIP() []byte {
	file_msgproto_msgdef_proto_rawDescOnce.Do(func() {
		file_msgproto_msgdef_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgproto_msgdef_proto_rawDescData)
	})
	return file_msgproto_msgdef_proto_rawDescData
}

var file_msgproto_msgdef_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msgproto_msgdef_proto_goTypes = []interface{}{
	(MsgType)(0), // 0: msg.MsgType
}
var file_msgproto_msgdef_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_msgproto_msgdef_proto_init() }
func file_msgproto_msgdef_proto_init() {
	if File_msgproto_msgdef_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgproto_msgdef_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgproto_msgdef_proto_goTypes,
		DependencyIndexes: file_msgproto_msgdef_proto_depIdxs,
		EnumInfos:         file_msgproto_msgdef_proto_enumTypes,
	}.Build()
	File_msgproto_msgdef_proto = out.File
	file_msgproto_msgdef_proto_rawDesc = nil
	file_msgproto_msgdef_proto_goTypes = nil
	file_msgproto_msgdef_proto_depIdxs = nil
}
