// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: msgproto/player.proto

package msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器负载类型
type ServerLoadType int32

const (
	ServerLoadType_Free    ServerLoadType = 0 //空闲
	ServerLoadType_Crowded ServerLoadType = 1 //拥挤
	ServerLoadType_Busy    ServerLoadType = 2 //繁忙
	ServerLoadType_Full    ServerLoadType = 3 //爆满
	ServerLoadType_Close   ServerLoadType = 4 //关服
)

// Enum value maps for ServerLoadType.
var (
	ServerLoadType_name = map[int32]string{
		0: "Free",
		1: "Crowded",
		2: "Busy",
		3: "Full",
		4: "Close",
	}
	ServerLoadType_value = map[string]int32{
		"Free":    0,
		"Crowded": 1,
		"Busy":    2,
		"Full":    3,
		"Close":   4,
	}
)

func (x ServerLoadType) Enum() *ServerLoadType {
	p := new(ServerLoadType)
	*p = x
	return p
}

func (x ServerLoadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerLoadType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgproto_player_proto_enumTypes[0].Descriptor()
}

func (ServerLoadType) Type() protoreflect.EnumType {
	return &file_msgproto_player_proto_enumTypes[0]
}

func (x ServerLoadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerLoadType.Descriptor instead.
func (ServerLoadType) EnumDescriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{0}
}

type LogoutType int32

const (
	LogoutType_Normal  LogoutType = 0 //正常退出
	LogoutType_Occupy  LogoutType = 1 //挤占&挤号
	LogoutType_KickOut LogoutType = 2 //被踢出去
)

// Enum value maps for LogoutType.
var (
	LogoutType_name = map[int32]string{
		0: "Normal",
		1: "Occupy",
		2: "KickOut",
	}
	LogoutType_value = map[string]int32{
		"Normal":  0,
		"Occupy":  1,
		"KickOut": 2,
	}
)

func (x LogoutType) Enum() *LogoutType {
	p := new(LogoutType)
	*p = x
	return p
}

func (x LogoutType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgproto_player_proto_enumTypes[1].Descriptor()
}

func (LogoutType) Type() protoreflect.EnumType {
	return &file_msgproto_player_proto_enumTypes[1]
}

func (x LogoutType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutType.Descriptor instead.
func (LogoutType) EnumDescriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{1}
}

// MsgLoadAttribute 5007
type MsgLoadAttribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapAttribute map[int32]int64 `protobuf:"bytes,1,rep,name=MapAttribute,proto3" json:"MapAttribute,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	SkillList    []*SkillData    `protobuf:"bytes,2,rep,name=SkillList,proto3" json:"SkillList,omitempty"`
}

func (x *MsgLoadAttribute) Reset() {
	*x = MsgLoadAttribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoadAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoadAttribute) ProtoMessage() {}

func (x *MsgLoadAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoadAttribute.ProtoReflect.Descriptor instead.
func (*MsgLoadAttribute) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{0}
}

func (x *MsgLoadAttribute) GetMapAttribute() map[int32]int64 {
	if x != nil {
		return x.MapAttribute
	}
	return nil
}

func (x *MsgLoadAttribute) GetSkillList() []*SkillData {
	if x != nil {
		return x.SkillList
	}
	return nil
}

// MsgLoadAppearance 5011
type MsgLoadAppearance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppearanceData []byte `protobuf:"bytes,1,opt,name=AppearanceData,proto3" json:"AppearanceData,omitempty"` //长度为0则是没有外观数据
	NickName       string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`             //昵称
	RoleConfigID   int32  `protobuf:"varint,3,opt,name=RoleConfigID,proto3" json:"RoleConfigID,omitempty"`    //配置ID
}

func (x *MsgLoadAppearance) Reset() {
	*x = MsgLoadAppearance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoadAppearance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoadAppearance) ProtoMessage() {}

func (x *MsgLoadAppearance) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoadAppearance.ProtoReflect.Descriptor instead.
func (*MsgLoadAppearance) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{1}
}

func (x *MsgLoadAppearance) GetAppearanceData() []byte {
	if x != nil {
		return x.AppearanceData
	}
	return nil
}

func (x *MsgLoadAppearance) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MsgLoadAppearance) GetRoleConfigID() int32 {
	if x != nil {
		return x.RoleConfigID
	}
	return 0
}

// MsgFillAppearanceReq 1008
type MsgFillAppearanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppearanceData []byte `protobuf:"bytes,1,opt,name=AppearanceData,proto3" json:"AppearanceData,omitempty"`
	NickName       string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`          //昵称
	RoleConfigID   int32  `protobuf:"varint,3,opt,name=RoleConfigID,proto3" json:"RoleConfigID,omitempty"` //配置ID
	Careers        int32  `protobuf:"varint,4,opt,name=Careers,proto3" json:"Careers,omitempty"`           //职业
}

func (x *MsgFillAppearanceReq) Reset() {
	*x = MsgFillAppearanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFillAppearanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFillAppearanceReq) ProtoMessage() {}

func (x *MsgFillAppearanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFillAppearanceReq.ProtoReflect.Descriptor instead.
func (*MsgFillAppearanceReq) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{2}
}

func (x *MsgFillAppearanceReq) GetAppearanceData() []byte {
	if x != nil {
		return x.AppearanceData
	}
	return nil
}

func (x *MsgFillAppearanceReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MsgFillAppearanceReq) GetRoleConfigID() int32 {
	if x != nil {
		return x.RoleConfigID
	}
	return 0
}

func (x *MsgFillAppearanceReq) GetCareers() int32 {
	if x != nil {
		return x.Careers
	}
	return 0
}

// MsgFillAppearanceRes 1009
type MsgFillAppearanceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"` // 0 成功
}

func (x *MsgFillAppearanceRes) Reset() {
	*x = MsgFillAppearanceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFillAppearanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFillAppearanceRes) ProtoMessage() {}

func (x *MsgFillAppearanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFillAppearanceRes.ProtoReflect.Descriptor instead.
func (*MsgFillAppearanceRes) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{3}
}

func (x *MsgFillAppearanceRes) GetRet() ErrCode {
	if x != nil {
		return x.Ret
	}
	return ErrCode_OK
}

// 勋章信息
type MsgMedalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MedalUnlockInfo          []byte            `protobuf:"bytes,1,opt,name=MedalUnlockInfo,proto3" json:"MedalUnlockInfo,omitempty"`                                                                                                             //勋章解锁信息-没有后置勋章
	MedalHaveAfterUnlockInfo map[uint32]uint32 `protobuf:"bytes,2,rep,name=MedalHaveAfterUnlockInfo,proto3" json:"MedalHaveAfterUnlockInfo,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //勋章解锁信息-有后置勋章 key:首个前置勋章 value:已激活的勋章ID
	MapMedalScore            map[int32]int32   `protobuf:"bytes,3,rep,name=MapMedalScore,proto3" json:"MapMedalScore,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`                       //勋章总评分新 key:勋章类型,对应keyword中EMedalType value:勋章总评分
}

func (x *MsgMedalInfo) Reset() {
	*x = MsgMedalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgMedalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMedalInfo) ProtoMessage() {}

func (x *MsgMedalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMedalInfo.ProtoReflect.Descriptor instead.
func (*MsgMedalInfo) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{4}
}

func (x *MsgMedalInfo) GetMedalUnlockInfo() []byte {
	if x != nil {
		return x.MedalUnlockInfo
	}
	return nil
}

func (x *MsgMedalInfo) GetMedalHaveAfterUnlockInfo() map[uint32]uint32 {
	if x != nil {
		return x.MedalHaveAfterUnlockInfo
	}
	return nil
}

func (x *MsgMedalInfo) GetMapMedalScore() map[int32]int32 {
	if x != nil {
		return x.MapMedalScore
	}
	return nil
}

// 单人副本信息
type SingleMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SingleMapChapterId int32 `protobuf:"varint,1,opt,name=SingleMapChapterId,proto3" json:"SingleMapChapterId,omitempty"` //单人副本关卡ID
	SingleMapLevelId   int32 `protobuf:"varint,2,opt,name=SingleMapLevelId,proto3" json:"SingleMapLevelId,omitempty"`     //单人副本地图等级ID
	EffectIndex        int32 `protobuf:"varint,3,opt,name=EffectIndex,proto3" json:"EffectIndex,omitempty"`               //选择能力的index
}

func (x *SingleMapInfo) Reset() {
	*x = SingleMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMapInfo) ProtoMessage() {}

func (x *SingleMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMapInfo.ProtoReflect.Descriptor instead.
func (*SingleMapInfo) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{5}
}

func (x *SingleMapInfo) GetSingleMapChapterId() int32 {
	if x != nil {
		return x.SingleMapChapterId
	}
	return 0
}

func (x *SingleMapInfo) GetSingleMapLevelId() int32 {
	if x != nil {
		return x.SingleMapLevelId
	}
	return 0
}

func (x *SingleMapInfo) GetEffectIndex() int32 {
	if x != nil {
		return x.EffectIndex
	}
	return 0
}

// 能力副本
type SparMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PetCfgId int32  `protobuf:"varint,1,opt,name=PetCfgId,proto3" json:"PetCfgId,omitempty"` //宠物Id，如果为0时表示
	SlotsId  uint32 `protobuf:"varint,2,opt,name=SlotsId,proto3" json:"SlotsId,omitempty"`   //挑战的槽位
	SparId   int32  `protobuf:"varint,3,opt,name=SparId,proto3" json:"SparId,omitempty"`     //能力Id
}

func (x *SparMapInfo) Reset() {
	*x = SparMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SparMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SparMapInfo) ProtoMessage() {}

func (x *SparMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SparMapInfo.ProtoReflect.Descriptor instead.
func (*SparMapInfo) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{6}
}

func (x *SparMapInfo) GetPetCfgId() int32 {
	if x != nil {
		return x.PetCfgId
	}
	return 0
}

func (x *SparMapInfo) GetSlotsId() uint32 {
	if x != nil {
		return x.SlotsId
	}
	return 0
}

func (x *SparMapInfo) GetSparId() int32 {
	if x != nil {
		return x.SparId
	}
	return 0
}

// 御灵道场副本
type SpiritDojoMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quality          int32   `protobuf:"varint,1,opt,name=Quality,proto3" json:"Quality,omitempty"`                          //关卡品质
	ChallengeTargets []int32 `protobuf:"varint,2,rep,packed,name=ChallengeTargets,proto3" json:"ChallengeTargets,omitempty"` //挑战目标信息
}

func (x *SpiritDojoMapInfo) Reset() {
	*x = SpiritDojoMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpiritDojoMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpiritDojoMapInfo) ProtoMessage() {}

func (x *SpiritDojoMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpiritDojoMapInfo.ProtoReflect.Descriptor instead.
func (*SpiritDojoMapInfo) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{7}
}

func (x *SpiritDojoMapInfo) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *SpiritDojoMapInfo) GetChallengeTargets() []int32 {
	if x != nil {
		return x.ChallengeTargets
	}
	return nil
}

// 关卡信息，玩家加载完成且已经在关卡时使用（断线重连）
type InMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapType           int32              `protobuf:"varint,1,opt,name=MapType,proto3" json:"MapType,omitempty"`
	MapStarted        bool               `protobuf:"varint,3,opt,name=MapStarted,proto3" json:"MapStarted,omitempty"`             //地图是否否已经开始
	LevelMapCfgKeyId  int32              `protobuf:"varint,4,opt,name=LevelMapCfgKeyId,proto3" json:"LevelMapCfgKeyId,omitempty"` //地图配置唯一ID
	EventId           uint64             `protobuf:"varint,5,opt,name=EventId,proto3" json:"EventId,omitempty"`                   //事件ID
	ThemeId           int32              `protobuf:"varint,6,opt,name=ThemeId,proto3" json:"ThemeId,omitempty"`
	InvadeEventObjId  uint64             `protobuf:"varint,7,opt,name=InvadeEventObjId,proto3" json:"InvadeEventObjId,omitempty"`   //战船战斗地图eventObjId
	PvpMirrorPlayerId uint64             `protobuf:"varint,8,opt,name=PvpMirrorPlayerId,proto3" json:"PvpMirrorPlayerId,omitempty"` //竞技场对手ID
	SingleInfo        *SingleMapInfo     `protobuf:"bytes,9,opt,name=SingleInfo,proto3" json:"SingleInfo,omitempty"`                //单人副本数据——不是单人副本则为nil
	SparInfo          *SparMapInfo       `protobuf:"bytes,10,opt,name=SparInfo,proto3" json:"SparInfo,omitempty"`                   //能力副本
	NihilityMode      int32              `protobuf:"varint,11,opt,name=NihilityMode,proto3" json:"NihilityMode,omitempty"`          //1简单  2困难  3无尽模式
	IsSummonPet       bool               `protobuf:"varint,12,opt,name=IsSummonPet,proto3" json:"IsSummonPet,omitempty"`            //是否已经召唤过宠物，执行ChangeBattlePetReq消息
	SpiritDojoInfo    *SpiritDojoMapInfo `protobuf:"bytes,13,opt,name=SpiritDojoInfo,proto3" json:"SpiritDojoInfo,omitempty"`       //御灵道场关卡信息
}

func (x *InMapInfo) Reset() {
	*x = InMapInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMapInfo) ProtoMessage() {}

func (x *InMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMapInfo.ProtoReflect.Descriptor instead.
func (*InMapInfo) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{8}
}

func (x *InMapInfo) GetMapType() int32 {
	if x != nil {
		return x.MapType
	}
	return 0
}

func (x *InMapInfo) GetMapStarted() bool {
	if x != nil {
		return x.MapStarted
	}
	return false
}

func (x *InMapInfo) GetLevelMapCfgKeyId() int32 {
	if x != nil {
		return x.LevelMapCfgKeyId
	}
	return 0
}

func (x *InMapInfo) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *InMapInfo) GetThemeId() int32 {
	if x != nil {
		return x.ThemeId
	}
	return 0
}

func (x *InMapInfo) GetInvadeEventObjId() uint64 {
	if x != nil {
		return x.InvadeEventObjId
	}
	return 0
}

func (x *InMapInfo) GetPvpMirrorPlayerId() uint64 {
	if x != nil {
		return x.PvpMirrorPlayerId
	}
	return 0
}

func (x *InMapInfo) GetSingleInfo() *SingleMapInfo {
	if x != nil {
		return x.SingleInfo
	}
	return nil
}

func (x *InMapInfo) GetSparInfo() *SparMapInfo {
	if x != nil {
		return x.SparInfo
	}
	return nil
}

func (x *InMapInfo) GetNihilityMode() int32 {
	if x != nil {
		return x.NihilityMode
	}
	return 0
}

func (x *InMapInfo) GetIsSummonPet() bool {
	if x != nil {
		return x.IsSummonPet
	}
	return false
}

func (x *InMapInfo) GetSpiritDojoInfo() *SpiritDojoMapInfo {
	if x != nil {
		return x.SpiritDojoInfo
	}
	return nil
}

type MsgLoadFinish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SysTime uint32 `protobuf:"varint,1,opt,name=SysTime,proto3" json:"SysTime,omitempty"` //系统时间
}

func (x *MsgLoadFinish) Reset() {
	*x = MsgLoadFinish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgLoadFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgLoadFinish) ProtoMessage() {}

func (x *MsgLoadFinish) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgLoadFinish.ProtoReflect.Descriptor instead.
func (*MsgLoadFinish) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{9}
}

func (x *MsgLoadFinish) GetSysTime() uint32 {
	if x != nil {
		return x.SysTime
	}
	return 0
}

type MsgNotifyLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason int32 `protobuf:"varint,1,opt,name=Reason,proto3" json:"Reason,omitempty"` //退出原因
}

func (x *MsgNotifyLogout) Reset() {
	*x = MsgNotifyLogout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgNotifyLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgNotifyLogout) ProtoMessage() {}

func (x *MsgNotifyLogout) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgNotifyLogout.ProtoReflect.Descriptor instead.
func (*MsgNotifyLogout) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{10}
}

func (x *MsgNotifyLogout) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type MsgSetPlayerInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=NickName,proto3" json:"NickName,omitempty"` //昵称
}

func (x *MsgSetPlayerInfoReq) Reset() {
	*x = MsgSetPlayerInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSetPlayerInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetPlayerInfoReq) ProtoMessage() {}

func (x *MsgSetPlayerInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetPlayerInfoReq.ProtoReflect.Descriptor instead.
func (*MsgSetPlayerInfoReq) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{11}
}

func (x *MsgSetPlayerInfoReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

type MsgSetPlayerInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret                 ErrCode `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	NickName            string  `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`                        //昵称
	ModifyNickNameCount int32   `protobuf:"varint,3,opt,name=ModifyNickNameCount,proto3" json:"ModifyNickNameCount,omitempty"` //修改昵称次数
}

func (x *MsgSetPlayerInfoRes) Reset() {
	*x = MsgSetPlayerInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSetPlayerInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSetPlayerInfoRes) ProtoMessage() {}

func (x *MsgSetPlayerInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSetPlayerInfoRes.ProtoReflect.Descriptor instead.
func (*MsgSetPlayerInfoRes) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{12}
}

func (x *MsgSetPlayerInfoRes) GetRet() ErrCode {
	if x != nil {
		return x.Ret
	}
	return ErrCode_OK
}

func (x *MsgSetPlayerInfoRes) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *MsgSetPlayerInfoRes) GetModifyNickNameCount() int32 {
	if x != nil {
		return x.ModifyNickNameCount
	}
	return 0
}

// 获取随机昵称
type MsgGetRandomNickNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgGetRandomNickNameReq) Reset() {
	*x = MsgGetRandomNickNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetRandomNickNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetRandomNickNameReq) ProtoMessage() {}

func (x *MsgGetRandomNickNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetRandomNickNameReq.ProtoReflect.Descriptor instead.
func (*MsgGetRandomNickNameReq) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{13}
}

type MsgGetRandomNickNameRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret          ErrCode  `protobuf:"varint,1,opt,name=Ret,proto3,enum=msg.ErrCode" json:"Ret,omitempty"`
	NickNameList []string `protobuf:"bytes,2,rep,name=NickNameList,proto3" json:"NickNameList,omitempty"`
}

func (x *MsgGetRandomNickNameRes) Reset() {
	*x = MsgGetRandomNickNameRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgGetRandomNickNameRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgGetRandomNickNameRes) ProtoMessage() {}

func (x *MsgGetRandomNickNameRes) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgGetRandomNickNameRes.ProtoReflect.Descriptor instead.
func (*MsgGetRandomNickNameRes) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{14}
}

func (x *MsgGetRandomNickNameRes) GetRet() ErrCode {
	if x != nil {
		return x.Ret
	}
	return ErrCode_OK
}

func (x *MsgGetRandomNickNameRes) GetNickNameList() []string {
	if x != nil {
		return x.NickNameList
	}
	return nil
}

// 通知修改昵称
type MsgModifyNickName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgModifyNickName) Reset() {
	*x = MsgModifyNickName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgproto_player_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgModifyNickName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgModifyNickName) ProtoMessage() {}

func (x *MsgModifyNickName) ProtoReflect() protoreflect.Message {
	mi := &file_msgproto_player_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgModifyNickName.ProtoReflect.Descriptor instead.
func (*MsgModifyNickName) Descriptor() ([]byte, []int) {
	return file_msgproto_player_proto_rawDescGZIP(), []int{15}
}

var File_msgproto_player_proto protoreflect.FileDescriptor

var file_msgproto_player_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x16, 0x6d, 0x73,
	0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6d, 0x73, 0x67, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x01, 0x0a, 0x10, 0x4d, 0x73,
	0x67, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x4b,
	0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73, 0x67, 0x4c, 0x6f,
	0x61, 0x64, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x4d,
	0x61, 0x70, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x3f, 0x0a, 0x11, 0x4d, 0x61, 0x70,
	0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x7b, 0x0a, 0x11, 0x4d, 0x73,
	0x67, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x26, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61,
	0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x22, 0x98, 0x01, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x46,
	0x69, 0x6c, 0x6c, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x26, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x41, 0x70, 0x70, 0x65, 0x61, 0x72,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x6f, 0x6c, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x65,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x61, 0x72, 0x65, 0x65,
	0x72, 0x73, 0x22, 0x36, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x41, 0x70, 0x70,
	0x65, 0x61, 0x72, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x03, 0x52, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x80, 0x03, 0x0a, 0x0c, 0x4d,
	0x73, 0x67, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x4d,
	0x65, 0x64, 0x61, 0x6c, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x55, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x6b, 0x0a, 0x18, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x48, 0x61,
	0x76, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x73,
	0x67, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x65, 0x64, 0x61, 0x6c,
	0x48, 0x61, 0x76, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x18, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x48,
	0x61, 0x76, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x4a, 0x0a, 0x0d, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x4d, 0x73, 0x67, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x61, 0x70,
	0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0d, 0x4d, 0x61, 0x70, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x1a, 0x4b,
	0x0a, 0x1d, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x48, 0x61, 0x76, 0x65, 0x41, 0x66, 0x74, 0x65, 0x72,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x40, 0x0a, 0x12, 0x4d,
	0x61, 0x70, 0x4d, 0x65, 0x64, 0x61, 0x6c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8d, 0x01,
	0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2e, 0x0a, 0x12, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x43, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x10, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x4d, 0x61, 0x70, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x45,
	0x66, 0x66, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x5b, 0x0a,
	0x0b, 0x53, 0x70, 0x61, 0x72, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x65, 0x74, 0x43, 0x66, 0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x50, 0x65, 0x74, 0x43, 0x66, 0x67, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6c, 0x6f, 0x74,
	0x73, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x53, 0x6c, 0x6f, 0x74, 0x73,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x70, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x53, 0x70, 0x61, 0x72, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x11, 0x53, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x44, 0x6f, 0x6a, 0x6f, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x18, 0x0a, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x68, 0x61,
	0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x10, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x73, 0x22, 0xe7, 0x03, 0x0a, 0x09, 0x49, 0x6e, 0x4d, 0x61, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x4d, 0x61, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a,
	0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x61, 0x70, 0x43, 0x66, 0x67, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x4d, 0x61,
	0x70, 0x43, 0x66, 0x67, 0x4b, 0x65, 0x79, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x54, 0x68, 0x65, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x2a, 0x0a,
	0x10, 0x49, 0x6e, 0x76, 0x61, 0x64, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x49,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x64, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x4f, 0x62, 0x6a, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x50, 0x76, 0x70,
	0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x50, 0x76, 0x70, 0x4d, 0x69, 0x72, 0x72, 0x6f, 0x72, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x08, 0x53,
	0x70, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x53, 0x70, 0x61, 0x72, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x53, 0x70, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x69, 0x68,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x4e, 0x69, 0x68, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x49, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x65, 0x74, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x50, 0x65, 0x74, 0x12,
	0x3e, 0x0a, 0x0e, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x44, 0x6f, 0x6a, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x70,
	0x69, 0x72, 0x69, 0x74, 0x44, 0x6f, 0x6a, 0x6f, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0e, 0x53, 0x70, 0x69, 0x72, 0x69, 0x74, 0x44, 0x6f, 0x6a, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x29, 0x0a, 0x0d, 0x4d, 0x73, 0x67, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x12, 0x18, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x07, 0x53, 0x79, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0f, 0x4d, 0x73,
	0x67, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x13, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x4d, 0x73, 0x67,
	0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x52, 0x65, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x13,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x13, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x19,
	0x0a, 0x17, 0x4d, 0x73, 0x67, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x69,
	0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x22, 0x5d, 0x0a, 0x17, 0x4d, 0x73, 0x67,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x03, 0x52, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x4e, 0x69, 0x63, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x4d, 0x73, 0x67, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x79, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x46, 0x0a,
	0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x72, 0x65, 0x65, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x72, 0x6f,
	0x77, 0x64, 0x65, 0x64, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x75, 0x73, 0x79, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x46, 0x75, 0x6c, 0x6c, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x10, 0x04, 0x2a, 0x31, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x79, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x4b,
	0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x10, 0x02, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x6d, 0x73,
	0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgproto_player_proto_rawDescOnce sync.Once
	file_msgproto_player_proto_rawDescData = file_msgproto_player_proto_rawDesc
)

func file_msgproto_player_proto_rawDescGZIP() []byte {
	file_msgproto_player_proto_rawDescOnce.Do(func() {
		file_msgproto_player_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgproto_player_proto_rawDescData)
	})
	return file_msgproto_player_proto_rawDescData
}

var file_msgproto_player_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msgproto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_msgproto_player_proto_goTypes = []interface{}{
	(ServerLoadType)(0),             // 0: msg.ServerLoadType
	(LogoutType)(0),                 // 1: msg.LogoutType
	(*MsgLoadAttribute)(nil),        // 2: msg.MsgLoadAttribute
	(*MsgLoadAppearance)(nil),       // 3: msg.MsgLoadAppearance
	(*MsgFillAppearanceReq)(nil),    // 4: msg.MsgFillAppearanceReq
	(*MsgFillAppearanceRes)(nil),    // 5: msg.MsgFillAppearanceRes
	(*MsgMedalInfo)(nil),            // 6: msg.MsgMedalInfo
	(*SingleMapInfo)(nil),           // 7: msg.SingleMapInfo
	(*SparMapInfo)(nil),             // 8: msg.SparMapInfo
	(*SpiritDojoMapInfo)(nil),       // 9: msg.SpiritDojoMapInfo
	(*InMapInfo)(nil),               // 10: msg.InMapInfo
	(*MsgLoadFinish)(nil),           // 11: msg.MsgLoadFinish
	(*MsgNotifyLogout)(nil),         // 12: msg.MsgNotifyLogout
	(*MsgSetPlayerInfoReq)(nil),     // 13: msg.MsgSetPlayerInfoReq
	(*MsgSetPlayerInfoRes)(nil),     // 14: msg.MsgSetPlayerInfoRes
	(*MsgGetRandomNickNameReq)(nil), // 15: msg.MsgGetRandomNickNameReq
	(*MsgGetRandomNickNameRes)(nil), // 16: msg.MsgGetRandomNickNameRes
	(*MsgModifyNickName)(nil),       // 17: msg.MsgModifyNickName
	nil,                             // 18: msg.MsgLoadAttribute.MapAttributeEntry
	nil,                             // 19: msg.MsgMedalInfo.MedalHaveAfterUnlockInfoEntry
	nil,                             // 20: msg.MsgMedalInfo.MapMedalScoreEntry
	(*SkillData)(nil),               // 21: msg.SkillData
	(ErrCode)(0),                    // 22: msg.ErrCode
}
var file_msgproto_player_proto_depIdxs = []int32{
	18, // 0: msg.MsgLoadAttribute.MapAttribute:type_name -> msg.MsgLoadAttribute.MapAttributeEntry
	21, // 1: msg.MsgLoadAttribute.SkillList:type_name -> msg.SkillData
	22, // 2: msg.MsgFillAppearanceRes.Ret:type_name -> msg.ErrCode
	19, // 3: msg.MsgMedalInfo.MedalHaveAfterUnlockInfo:type_name -> msg.MsgMedalInfo.MedalHaveAfterUnlockInfoEntry
	20, // 4: msg.MsgMedalInfo.MapMedalScore:type_name -> msg.MsgMedalInfo.MapMedalScoreEntry
	7,  // 5: msg.InMapInfo.SingleInfo:type_name -> msg.SingleMapInfo
	8,  // 6: msg.InMapInfo.SparInfo:type_name -> msg.SparMapInfo
	9,  // 7: msg.InMapInfo.SpiritDojoInfo:type_name -> msg.SpiritDojoMapInfo
	22, // 8: msg.MsgSetPlayerInfoRes.Ret:type_name -> msg.ErrCode
	22, // 9: msg.MsgGetRandomNickNameRes.Ret:type_name -> msg.ErrCode
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_msgproto_player_proto_init() }
func file_msgproto_player_proto_init() {
	if File_msgproto_player_proto != nil {
		return
	}
	file_msgproto_errcode_proto_init()
	file_msgproto_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msgproto_player_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoadAttribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoadAppearance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFillAppearanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFillAppearanceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgMedalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SparMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpiritDojoMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InMapInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgLoadFinish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgNotifyLogout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSetPlayerInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSetPlayerInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetRandomNickNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgGetRandomNickNameRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgproto_player_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgModifyNickName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgproto_player_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgproto_player_proto_goTypes,
		DependencyIndexes: file_msgproto_player_proto_depIdxs,
		EnumInfos:         file_msgproto_player_proto_enumTypes,
		MessageInfos:      file_msgproto_player_proto_msgTypes,
	}.Build()
	File_msgproto_player_proto = out.File
	file_msgproto_player_proto_rawDesc = nil
	file_msgproto_player_proto_goTypes = nil
	file_msgproto_player_proto_depIdxs = nil
}
