// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: rpcproto/login.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginStatus int32

const (
	LoginStatus_Logining    LoginStatus = 0
	LoginStatus_Logined     LoginStatus = 1
	LoginStatus_LoginOuting LoginStatus = 2
	LoginStatus_LoginOuted  LoginStatus = 3
)

// Enum value maps for LoginStatus.
var (
	LoginStatus_name = map[int32]string{
		0: "Logining",
		1: "Logined",
		2: "LoginOuting",
		3: "LoginOuted",
	}
	LoginStatus_value = map[string]int32{
		"Logining":    0,
		"Logined":     1,
		"LoginOuting": 2,
		"LoginOuted":  3,
	}
)

func (x LoginStatus) Enum() *LoginStatus {
	p := new(LoginStatus)
	*p = x
	return p
}

func (x LoginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rpcproto_login_proto_enumTypes[0].Descriptor()
}

func (LoginStatus) Type() protoreflect.EnumType {
	return &file_rpcproto_login_proto_enumTypes[0]
}

func (x LoginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginStatus.Descriptor instead.
func (LoginStatus) EnumDescriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{0}
}

type LoginType int32

const (
	LoginType_Gust          LoginType = 0
	LoginType_Account       LoginType = 1
	LoginType_TapTap        LoginType = 2
	LoginType_Facebook      LoginType = 3
	LoginType_Google        LoginType = 4
	LoginType_Fusion        LoginType = 5 //动游聚合
	LoginType_LoginType_Max LoginType = 6
)

// Enum value maps for LoginType.
var (
	LoginType_name = map[int32]string{
		0: "Gust",
		1: "Account",
		2: "TapTap",
		3: "Facebook",
		4: "Google",
		5: "Fusion",
		6: "LoginType_Max",
	}
	LoginType_value = map[string]int32{
		"Gust":          0,
		"Account":       1,
		"TapTap":        2,
		"Facebook":      3,
		"Google":        4,
		"Fusion":        5,
		"LoginType_Max": 6,
	}
)

func (x LoginType) Enum() *LoginType {
	p := new(LoginType)
	*p = x
	return p
}

func (x LoginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpcproto_login_proto_enumTypes[1].Descriptor()
}

func (LoginType) Type() protoreflect.EnumType {
	return &file_rpcproto_login_proto_enumTypes[1]
}

func (x LoginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginType.Descriptor instead.
func (LoginType) EnumDescriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{1}
}

type LoginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatType       LoginType `protobuf:"varint,1,opt,name=PlatType,proto3,enum=rpc.LoginType" json:"PlatType,omitempty"`
	PlatId         string    `protobuf:"bytes,2,opt,name=PlatId,proto3" json:"PlatId,omitempty"`
	AccessToken    string    `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	GameId         string    `protobuf:"bytes,4,opt,name=GameId,proto3" json:"GameId,omitempty"`
	ActiveCode     string    `protobuf:"bytes,5,opt,name=ActiveCode,proto3" json:"ActiveCode,omitempty"`
	UserName       string    `protobuf:"bytes,6,opt,name=UserName,proto3" json:"UserName,omitempty"`
	LoginCheckTime int64     `protobuf:"varint,7,opt,name=LoginCheckTime,proto3" json:"LoginCheckTime,omitempty"`
	Sign           string    `protobuf:"bytes,8,opt,name=Sign,proto3" json:"Sign,omitempty"`              //登录签名
	ChanneCode     int32     `protobuf:"varint,9,opt,name=ChanneCode,proto3" json:"ChanneCode,omitempty"` //渠道
	ChannePlat     string    `protobuf:"bytes,10,opt,name=ChannePlat,proto3" json:"ChannePlat,omitempty"` //渠道码(平台id)
}

func (x *LoginInfo) Reset() {
	*x = LoginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInfo) ProtoMessage() {}

func (x *LoginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInfo.ProtoReflect.Descriptor instead.
func (*LoginInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginInfo) GetPlatType() LoginType {
	if x != nil {
		return x.PlatType
	}
	return LoginType_Gust
}

func (x *LoginInfo) GetPlatId() string {
	if x != nil {
		return x.PlatId
	}
	return ""
}

func (x *LoginInfo) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginInfo) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *LoginInfo) GetActiveCode() string {
	if x != nil {
		return x.ActiveCode
	}
	return ""
}

func (x *LoginInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginInfo) GetLoginCheckTime() int64 {
	if x != nil {
		return x.LoginCheckTime
	}
	return 0
}

func (x *LoginInfo) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *LoginInfo) GetChanneCode() int32 {
	if x != nil {
		return x.ChanneCode
	}
	return 0
}

func (x *LoginInfo) GetChannePlat() string {
	if x != nil {
		return x.ChannePlat
	}
	return ""
}

// 数据库返回结果
type LoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatType    LoginType `protobuf:"varint,1,opt,name=PlatType,proto3,enum=rpc.LoginType" json:"PlatType,omitempty"`
	PlatId      string    `protobuf:"bytes,2,opt,name=PlatId,proto3" json:"PlatId,omitempty"`
	AccessToken string    `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	Ret         int32     `protobuf:"varint,4,opt,name=Ret,proto3" json:"Ret,omitempty"`
}

func (x *LoginResult) Reset() {
	*x = LoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResult) ProtoMessage() {}

func (x *LoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResult.ProtoReflect.Descriptor instead.
func (*LoginResult) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResult) GetPlatType() LoginType {
	if x != nil {
		return x.PlatType
	}
	return LoginType_Gust
}

func (x *LoginResult) GetPlatId() string {
	if x != nil {
		return x.PlatId
	}
	return ""
}

func (x *LoginResult) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResult) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 选服请求
type ChoseServerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *ChoseServerReq) Reset() {
	*x = ChoseServerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoseServerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoseServerReq) ProtoMessage() {}

func (x *ChoseServerReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoseServerReq.ProtoReflect.Descriptor instead.
func (*ChoseServerReq) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{2}
}

func (x *ChoseServerReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 选服返回结果
type ChoseServerRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Ret   int32  `protobuf:"varint,2,opt,name=Ret,proto3" json:"Ret,omitempty"`
}

func (x *ChoseServerRet) Reset() {
	*x = ChoseServerRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChoseServerRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoseServerRet) ProtoMessage() {}

func (x *ChoseServerRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoseServerRet.ProtoReflect.Descriptor instead.
func (*ChoseServerRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{3}
}

func (x *ChoseServerRet) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChoseServerRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 登陆网关Token验证请求
type LoginGateCheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	ClientIp    string `protobuf:"bytes,2,opt,name=ClientIp,proto3" json:"ClientIp,omitempty"`       // Ip
	ChannePlat  string `protobuf:"bytes,3,opt,name=ChannePlat,proto3" json:"ChannePlat,omitempty"`   //渠道码(平台id)
	ChannelUUID string `protobuf:"bytes,4,opt,name=ChannelUUID,proto3" json:"ChannelUUID,omitempty"` //玩家渠道openid或UUID
	ShowAreaId  int32  `protobuf:"varint,5,opt,name=ShowAreaId,proto3" json:"ShowAreaId,omitempty"`  // 玩家登录的显示区服
}

func (x *LoginGateCheckReq) Reset() {
	*x = LoginGateCheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGateCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGateCheckReq) ProtoMessage() {}

func (x *LoginGateCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGateCheckReq.ProtoReflect.Descriptor instead.
func (*LoginGateCheckReq) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{4}
}

func (x *LoginGateCheckReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginGateCheckReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LoginGateCheckReq) GetChannePlat() string {
	if x != nil {
		return x.ChannePlat
	}
	return ""
}

func (x *LoginGateCheckReq) GetChannelUUID() string {
	if x != nil {
		return x.ChannelUUID
	}
	return ""
}

func (x *LoginGateCheckReq) GetShowAreaId() int32 {
	if x != nil {
		return x.ShowAreaId
	}
	return 0
}

// 登陆网关Token验证结果返回
type LoginGateCheckRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"` // GameService nodeId
	GSName string `protobuf:"bytes,2,opt,name=GSName,proto3" json:"GSName,omitempty"`
	Ret    int32  `protobuf:"varint,3,opt,name=Ret,proto3" json:"Ret,omitempty"`
}

func (x *LoginGateCheckRet) Reset() {
	*x = LoginGateCheckRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginGateCheckRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginGateCheckRet) ProtoMessage() {}

func (x *LoginGateCheckRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginGateCheckRet.ProtoReflect.Descriptor instead.
func (*LoginGateCheckRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{5}
}

func (x *LoginGateCheckRet) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LoginGateCheckRet) GetGSName() string {
	if x != nil {
		return x.GSName
	}
	return ""
}

func (x *LoginGateCheckRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 请求登陆到GameService
type LoginToGameServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateNodeId string `protobuf:"bytes,1,opt,name=GateNodeId,proto3" json:"GateNodeId,omitempty"`
	ClientId   string `protobuf:"bytes,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SessionId  string `protobuf:"bytes,4,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	Ip         string `protobuf:"bytes,5,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Os         string `protobuf:"bytes,6,opt,name=Os,proto3" json:"Os,omitempty"`
}

func (x *LoginToGameServiceReq) Reset() {
	*x = LoginToGameServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginToGameServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginToGameServiceReq) ProtoMessage() {}

func (x *LoginToGameServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginToGameServiceReq.ProtoReflect.Descriptor instead.
func (*LoginToGameServiceReq) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{6}
}

func (x *LoginToGameServiceReq) GetGateNodeId() string {
	if x != nil {
		return x.GateNodeId
	}
	return ""
}

func (x *LoginToGameServiceReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LoginToGameServiceReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginToGameServiceReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginToGameServiceReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *LoginToGameServiceReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

// GameService返回登陆结果
type LoginToGameServiceRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`      // 0表示成功 1 登陆会话不存在，重新走登陆流程  2登陆Token错误
	NodeId    string `protobuf:"bytes,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"` // GameService nodeId
	SessionId string `protobuf:"bytes,3,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
}

func (x *LoginToGameServiceRet) Reset() {
	*x = LoginToGameServiceRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginToGameServiceRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginToGameServiceRet) ProtoMessage() {}

func (x *LoginToGameServiceRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginToGameServiceRet.ProtoReflect.Descriptor instead.
func (*LoginToGameServiceRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{7}
}

func (x *LoginToGameServiceRet) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *LoginToGameServiceRet) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LoginToGameServiceRet) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GameService->CenterService同步玩家状态
type UpdatePlayerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string      `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	GSName string      `protobuf:"bytes,2,opt,name=GSName,proto3" json:"GSName,omitempty"`
	UserId string      `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Status LoginStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=rpc.LoginStatus" json:"Status,omitempty"`
}

func (x *UpdatePlayerStatus) Reset() {
	*x = UpdatePlayerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerStatus) ProtoMessage() {}

func (x *UpdatePlayerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerStatus.ProtoReflect.Descriptor instead.
func (*UpdatePlayerStatus) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePlayerStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdatePlayerStatus) GetGSName() string {
	if x != nil {
		return x.GSName
	}
	return ""
}

func (x *UpdatePlayerStatus) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdatePlayerStatus) GetStatus() LoginStatus {
	if x != nil {
		return x.Status
	}
	return LoginStatus_Logining
}

type GsLoginResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  string `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=SessionId,proto3" json:"SessionId,omitempty"`
	UserId    string `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *GsLoginResult) Reset() {
	*x = GsLoginResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_login_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GsLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GsLoginResult) ProtoMessage() {}

func (x *GsLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_login_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GsLoginResult.ProtoReflect.Descriptor instead.
func (*GsLoginResult) Descriptor() ([]byte, []int) {
	return file_rpcproto_login_proto_rawDescGZIP(), []int{9}
}

func (x *GsLoginResult) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GsLoginResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GsLoginResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_rpcproto_login_proto protoreflect.FileDescriptor

var file_rpcproto_login_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0xc1, 0x02, 0x0a, 0x09,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x0a, 0x08, 0x50, 0x6c, 0x61,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x50, 0x6c, 0x61,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x49, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53,
	0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x22,
	0x85, 0x01, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50,
	0x6c, 0x61, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0x28, 0x0a, 0x0e, 0x43, 0x68, 0x6f, 0x73, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x38, 0x0a, 0x0e, 0x43, 0x68, 0x6f, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0xa9, 0x01, 0x0a, 0x11,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x50,
	0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x50, 0x6c, 0x61, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x68, 0x6f, 0x77, 0x41,
	0x72, 0x65, 0x61, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x68, 0x6f,
	0x77, 0x41, 0x72, 0x65, 0x61, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x47, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x52, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x52, 0x65, 0x74, 0x22, 0xa9,
	0x01, 0x0a, 0x15, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x61, 0x74, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x61,
	0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x4f, 0x73, 0x22, 0x5f, 0x0a, 0x15, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x54, 0x6f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x12,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x53,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x53, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x61, 0x0a, 0x0d, 0x47, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x2a, 0x49, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x65, 0x64, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x69, 0x6e, 0x67,
	0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x65, 0x64,
	0x10, 0x03, 0x2a, 0x67, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x08, 0x0a, 0x04, 0x47, 0x75, 0x73, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x61, 0x70, 0x54, 0x61, 0x70,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x10, 0x03,
	0x12, 0x0a, 0x0a, 0x06, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x06, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcproto_login_proto_rawDescOnce sync.Once
	file_rpcproto_login_proto_rawDescData = file_rpcproto_login_proto_rawDesc
)

func file_rpcproto_login_proto_rawDescGZIP() []byte {
	file_rpcproto_login_proto_rawDescOnce.Do(func() {
		file_rpcproto_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcproto_login_proto_rawDescData)
	})
	return file_rpcproto_login_proto_rawDescData
}

var file_rpcproto_login_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpcproto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_rpcproto_login_proto_goTypes = []interface{}{
	(LoginStatus)(0),              // 0: rpc.LoginStatus
	(LoginType)(0),                // 1: rpc.LoginType
	(*LoginInfo)(nil),             // 2: rpc.LoginInfo
	(*LoginResult)(nil),           // 3: rpc.LoginResult
	(*ChoseServerReq)(nil),        // 4: rpc.ChoseServerReq
	(*ChoseServerRet)(nil),        // 5: rpc.ChoseServerRet
	(*LoginGateCheckReq)(nil),     // 6: rpc.LoginGateCheckReq
	(*LoginGateCheckRet)(nil),     // 7: rpc.LoginGateCheckRet
	(*LoginToGameServiceReq)(nil), // 8: rpc.LoginToGameServiceReq
	(*LoginToGameServiceRet)(nil), // 9: rpc.LoginToGameServiceRet
	(*UpdatePlayerStatus)(nil),    // 10: rpc.UpdatePlayerStatus
	(*GsLoginResult)(nil),         // 11: rpc.GsLoginResult
}
var file_rpcproto_login_proto_depIdxs = []int32{
	1, // 0: rpc.LoginInfo.PlatType:type_name -> rpc.LoginType
	1, // 1: rpc.LoginResult.PlatType:type_name -> rpc.LoginType
	0, // 2: rpc.UpdatePlayerStatus.Status:type_name -> rpc.LoginStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rpcproto_login_proto_init() }
func file_rpcproto_login_proto_init() {
	if File_rpcproto_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcproto_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoseServerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChoseServerRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGateCheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginGateCheckRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginToGameServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginToGameServiceRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_login_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GsLoginResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcproto_login_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcproto_login_proto_goTypes,
		DependencyIndexes: file_rpcproto_login_proto_depIdxs,
		EnumInfos:         file_rpcproto_login_proto_enumTypes,
		MessageInfos:      file_rpcproto_login_proto_msgTypes,
	}.Build()
	File_rpcproto_login_proto = out.File
	file_rpcproto_login_proto_rawDesc = nil
	file_rpcproto_login_proto_goTypes = nil
	file_rpcproto_login_proto_depIdxs = nil
}
