// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: rpcproto/servicestatus.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GameService->CenterService同步负载情况
type GameServiceBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	GSName string `protobuf:"bytes,2,opt,name=GSName,proto3" json:"GSName,omitempty"`
	Weigh  int32  `protobuf:"varint,3,opt,name=Weigh,proto3" json:"Weigh,omitempty"`
}

func (x *GameServiceBalance) Reset() {
	*x = GameServiceBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServiceBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServiceBalance) ProtoMessage() {}

func (x *GameServiceBalance) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServiceBalance.ProtoReflect.Descriptor instead.
func (*GameServiceBalance) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{0}
}

func (x *GameServiceBalance) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GameServiceBalance) GetGSName() string {
	if x != nil {
		return x.GSName
	}
	return ""
}

func (x *GameServiceBalance) GetWeigh() int32 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

// GameService->CenterService刷新所有玩家的列表
type UpdatePlayerList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string   `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	UList  []string `protobuf:"bytes,2,rep,name=UList,proto3" json:"UList,omitempty"`
	GSName string   `protobuf:"bytes,3,opt,name=GSName,proto3" json:"GSName,omitempty"`
}

func (x *UpdatePlayerList) Reset() {
	*x = UpdatePlayerList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerList) ProtoMessage() {}

func (x *UpdatePlayerList) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerList.ProtoReflect.Descriptor instead.
func (*UpdatePlayerList) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePlayerList) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdatePlayerList) GetUList() []string {
	if x != nil {
		return x.UList
	}
	return nil
}

func (x *UpdatePlayerList) GetGSName() string {
	if x != nil {
		return x.GSName
	}
	return ""
}

// GateService->HttpGateService同步负载
type GateBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	Weigh  int32  `protobuf:"varint,2,opt,name=Weigh,proto3" json:"Weigh,omitempty"`
}

func (x *GateBalance) Reset() {
	*x = GateBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateBalance) ProtoMessage() {}

func (x *GateBalance) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateBalance.ProtoReflect.Descriptor instead.
func (*GateBalance) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{2}
}

func (x *GateBalance) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GateBalance) GetWeigh() int32 {
	if x != nil {
		return x.Weigh
	}
	return 0
}

// GateService链接信息
type GateServiceConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConnectNum int32  `protobuf:"varint,1,opt,name=ConnectNum,proto3" json:"ConnectNum,omitempty"` //链接数量
	ClientNum  int32  `protobuf:"varint,2,opt,name=ClientNum,proto3" json:"ClientNum,omitempty"`   //客户端链接数
	Error      string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *GateServiceConnect) Reset() {
	*x = GateServiceConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GateServiceConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateServiceConnect) ProtoMessage() {}

func (x *GateServiceConnect) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateServiceConnect.ProtoReflect.Descriptor instead.
func (*GateServiceConnect) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{3}
}

func (x *GateServiceConnect) GetConnectNum() int32 {
	if x != nil {
		return x.ConnectNum
	}
	return 0
}

func (x *GateServiceConnect) GetClientNum() int32 {
	if x != nil {
		return x.ClientNum
	}
	return 0
}

func (x *GateServiceConnect) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GameService玩家数量信息
type GameServicePlayerCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerObjNum     int32 `protobuf:"varint,1,opt,name=PlayerObjNum,proto3" json:"PlayerObjNum,omitempty"`         //玩家对象数量
	PlayerConnectNum int32 `protobuf:"varint,2,opt,name=PlayerConnectNum,proto3" json:"PlayerConnectNum,omitempty"` //玩家链接上的数量
}

func (x *GameServicePlayerCount) Reset() {
	*x = GameServicePlayerCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServicePlayerCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServicePlayerCount) ProtoMessage() {}

func (x *GameServicePlayerCount) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServicePlayerCount.ProtoReflect.Descriptor instead.
func (*GameServicePlayerCount) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{4}
}

func (x *GameServicePlayerCount) GetPlayerObjNum() int32 {
	if x != nil {
		return x.PlayerObjNum
	}
	return 0
}

func (x *GameServicePlayerCount) GetPlayerConnectNum() int32 {
	if x != nil {
		return x.PlayerConnectNum
	}
	return 0
}

type CenterServerBalanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId    string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	GSName    string `protobuf:"bytes,2,opt,name=GSName,proto3" json:"GSName,omitempty"`
	Weight    int32  `protobuf:"varint,3,opt,name=Weight,proto3" json:"Weight,omitempty"`
	SelectNum uint64 `protobuf:"varint,4,opt,name=SelectNum,proto3" json:"SelectNum,omitempty"`
}

func (x *CenterServerBalanceInfo) Reset() {
	*x = CenterServerBalanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CenterServerBalanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CenterServerBalanceInfo) ProtoMessage() {}

func (x *CenterServerBalanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CenterServerBalanceInfo.ProtoReflect.Descriptor instead.
func (*CenterServerBalanceInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{5}
}

func (x *CenterServerBalanceInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CenterServerBalanceInfo) GetGSName() string {
	if x != nil {
		return x.GSName
	}
	return ""
}

func (x *CenterServerBalanceInfo) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CenterServerBalanceInfo) GetSelectNum() uint64 {
	if x != nil {
		return x.SelectNum
	}
	return 0
}

type MsgCenterServerBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CenterBalanceList []*CenterServerBalanceInfo `protobuf:"bytes,1,rep,name=CenterBalanceList,proto3" json:"CenterBalanceList,omitempty"`
}

func (x *MsgCenterServerBalance) Reset() {
	*x = MsgCenterServerBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgCenterServerBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCenterServerBalance) ProtoMessage() {}

func (x *MsgCenterServerBalance) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCenterServerBalance.ProtoReflect.Descriptor instead.
func (*MsgCenterServerBalance) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{6}
}

func (x *MsgCenterServerBalance) GetCenterBalanceList() []*CenterServerBalanceInfo {
	if x != nil {
		return x.CenterBalanceList
	}
	return nil
}

type MsgAllServerNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeIdList []string `protobuf:"bytes,1,rep,name=NodeIdList,proto3" json:"NodeIdList,omitempty"`
}

func (x *MsgAllServerNode) Reset() {
	*x = MsgAllServerNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAllServerNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAllServerNode) ProtoMessage() {}

func (x *MsgAllServerNode) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAllServerNode.ProtoReflect.Descriptor instead.
func (*MsgAllServerNode) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{7}
}

func (x *MsgAllServerNode) GetNodeIdList() []string {
	if x != nil {
		return x.NodeIdList
	}
	return nil
}

type SaveAreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatId string `protobuf:"bytes,1,opt,name=PlatId,proto3" json:"PlatId,omitempty"`
}

func (x *SaveAreaInfo) Reset() {
	*x = SaveAreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveAreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveAreaInfo) ProtoMessage() {}

func (x *SaveAreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveAreaInfo.ProtoReflect.Descriptor instead.
func (*SaveAreaInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{8}
}

func (x *SaveAreaInfo) GetPlatId() string {
	if x != nil {
		return x.PlatId
	}
	return ""
}

type AreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaId       int32  `protobuf:"varint,1,opt,name=AreaId,proto3" json:"AreaId,omitempty"`
	CenterNodeId string `protobuf:"bytes,2,opt,name=CenterNodeId,proto3" json:"CenterNodeId,omitempty"`
}

func (x *AreaInfo) Reset() {
	*x = AreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaInfo) ProtoMessage() {}

func (x *AreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaInfo.ProtoReflect.Descriptor instead.
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{9}
}

func (x *AreaInfo) GetAreaId() int32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *AreaInfo) GetCenterNodeId() string {
	if x != nil {
		return x.CenterNodeId
	}
	return ""
}

type GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId          string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	GameServiceName string `protobuf:"bytes,2,opt,name=GameServiceName,proto3" json:"GameServiceName,omitempty"`
}

func (x *GameInfo) Reset() {
	*x = GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInfo) ProtoMessage() {}

func (x *GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInfo.ProtoReflect.Descriptor instead.
func (*GameInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{10}
}

func (x *GameInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GameInfo) GetGameServiceName() string {
	if x != nil {
		return x.GameServiceName
	}
	return ""
}

type GetGameNodePlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 以下保留字段
	NodeId      string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	// 使用字段
	Error     string `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
	ConnNum   int32  `protobuf:"varint,4,opt,name=ConnNum,proto3" json:"ConnNum,omitempty"`
	PlayerNum int32  `protobuf:"varint,5,opt,name=PlayerNum,proto3" json:"PlayerNum,omitempty"`
}

func (x *GetGameNodePlayerInfo) Reset() {
	*x = GetGameNodePlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameNodePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameNodePlayerInfo) ProtoMessage() {}

func (x *GetGameNodePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameNodePlayerInfo.ProtoReflect.Descriptor instead.
func (*GetGameNodePlayerInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{11}
}

func (x *GetGameNodePlayerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetGameNodePlayerInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetGameNodePlayerInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetGameNodePlayerInfo) GetConnNum() int32 {
	if x != nil {
		return x.ConnNum
	}
	return 0
}

func (x *GetGameNodePlayerInfo) GetPlayerNum() int32 {
	if x != nil {
		return x.PlayerNum
	}
	return 0
}

// 获取节点连接信息
type GameNodePlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServiceInfo []*GameInfo `protobuf:"bytes,1,rep,name=GameServiceInfo,proto3" json:"GameServiceInfo,omitempty"`
}

func (x *GameNodePlayerInfo) Reset() {
	*x = GameNodePlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameNodePlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNodePlayerInfo) ProtoMessage() {}

func (x *GameNodePlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNodePlayerInfo.ProtoReflect.Descriptor instead.
func (*GameNodePlayerInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{12}
}

func (x *GameNodePlayerInfo) GetGameServiceInfo() []*GameInfo {
	if x != nil {
		return x.GameServiceInfo
	}
	return nil
}

type GameNodePlayerInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultList []*GetGameNodePlayerInfo `protobuf:"bytes,1,rep,name=ResultList,proto3" json:"ResultList,omitempty"`
}

func (x *GameNodePlayerInfoResult) Reset() {
	*x = GameNodePlayerInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameNodePlayerInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameNodePlayerInfoResult) ProtoMessage() {}

func (x *GameNodePlayerInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameNodePlayerInfoResult.ProtoReflect.Descriptor instead.
func (*GameNodePlayerInfoResult) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{13}
}

func (x *GameNodePlayerInfoResult) GetResultList() []*GetGameNodePlayerInfo {
	if x != nil {
		return x.ResultList
	}
	return nil
}

// 获取网关连接信息
type GetGateServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateList []string `protobuf:"bytes,1,rep,name=GateList,proto3" json:"GateList,omitempty"`
}

func (x *GetGateServiceInfo) Reset() {
	*x = GetGateServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGateServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateServiceInfo) ProtoMessage() {}

func (x *GetGateServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateServiceInfo.ProtoReflect.Descriptor instead.
func (*GetGateServiceInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{14}
}

func (x *GetGateServiceInfo) GetGateList() []string {
	if x != nil {
		return x.GateList
	}
	return nil
}

type GetGateServiceInfoResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GateResultList []*GateServiceConnect `protobuf:"bytes,1,rep,name=GateResultList,proto3" json:"GateResultList,omitempty"`
}

func (x *GetGateServiceInfoResult) Reset() {
	*x = GetGateServiceInfoResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGateServiceInfoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGateServiceInfoResult) ProtoMessage() {}

func (x *GetGateServiceInfoResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGateServiceInfoResult.ProtoReflect.Descriptor instead.
func (*GetGateServiceInfoResult) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{15}
}

func (x *GetGateServiceInfoResult) GetGateResultList() []*GateServiceConnect {
	if x != nil {
		return x.GateResultList
	}
	return nil
}

type CallRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   []byte `protobuf:"bytes,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *CallRet) Reset() {
	*x = CallRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRet) ProtoMessage() {}

func (x *CallRet) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRet.ProtoReflect.Descriptor instead.
func (*CallRet) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{16}
}

func (x *CallRet) GetRet() []byte {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *CallRet) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// NodeId下面所有的服务
type ServiceNameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapServiceNameInfo map[string]*CallRet `protobuf:"bytes,1,rep,name=MapServiceNameInfo,proto3" json:"MapServiceNameInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ServiceNameInfo) Reset() {
	*x = ServiceNameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceNameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNameInfo) ProtoMessage() {}

func (x *ServiceNameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNameInfo.ProtoReflect.Descriptor instead.
func (*ServiceNameInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{17}
}

func (x *ServiceNameInfo) GetMapServiceNameInfo() map[string]*CallRet {
	if x != nil {
		return x.MapServiceNameInfo
	}
	return nil
}

type CallAreaServiceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AreaServiceInfo []*CallAreaServiceInfo `protobuf:"bytes,1,rep,name=AreaServiceInfo,proto3" json:"AreaServiceInfo,omitempty"`
}

func (x *CallAreaServiceReq) Reset() {
	*x = CallAreaServiceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAreaServiceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAreaServiceReq) ProtoMessage() {}

func (x *CallAreaServiceReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAreaServiceReq.ProtoReflect.Descriptor instead.
func (*CallAreaServiceReq) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{18}
}

func (x *CallAreaServiceReq) GetAreaServiceInfo() []*CallAreaServiceInfo {
	if x != nil {
		return x.AreaServiceInfo
	}
	return nil
}

type CallAreaServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId      string `protobuf:"bytes,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=ServiceName,proto3" json:"ServiceName,omitempty"`
	MethodName  string `protobuf:"bytes,3,opt,name=MethodName,proto3" json:"MethodName,omitempty"`
	InParam     []byte `protobuf:"bytes,4,opt,name=InParam,proto3" json:"InParam,omitempty"`
}

func (x *CallAreaServiceInfo) Reset() {
	*x = CallAreaServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAreaServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAreaServiceInfo) ProtoMessage() {}

func (x *CallAreaServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAreaServiceInfo.ProtoReflect.Descriptor instead.
func (*CallAreaServiceInfo) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{19}
}

func (x *CallAreaServiceInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CallAreaServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CallAreaServiceInfo) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *CallAreaServiceInfo) GetInParam() []byte {
	if x != nil {
		return x.InParam
	}
	return nil
}

type CallAreaServiceRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapServiceInfo map[string]*ServiceNameInfo `protobuf:"bytes,1,rep,name=MapServiceInfo,proto3" json:"MapServiceInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CallAreaServiceRes) Reset() {
	*x = CallAreaServiceRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallAreaServiceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallAreaServiceRes) ProtoMessage() {}

func (x *CallAreaServiceRes) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallAreaServiceRes.ProtoReflect.Descriptor instead.
func (*CallAreaServiceRes) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{20}
}

func (x *CallAreaServiceRes) GetMapServiceInfo() map[string]*ServiceNameInfo {
	if x != nil {
		return x.MapServiceInfo
	}
	return nil
}

type PlayerMaxStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegisterIsFull bool `protobuf:"varint,1,opt,name=RegisterIsFull,proto3" json:"RegisterIsFull,omitempty"` //注册是否已经达到上限
	OnlineIsFull   bool `protobuf:"varint,2,opt,name=OnlineIsFull,proto3" json:"OnlineIsFull,omitempty"`     //在线人数是否已经达到上限
}

func (x *PlayerMaxStatus) Reset() {
	*x = PlayerMaxStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcproto_servicestatus_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMaxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMaxStatus) ProtoMessage() {}

func (x *PlayerMaxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rpcproto_servicestatus_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMaxStatus.ProtoReflect.Descriptor instead.
func (*PlayerMaxStatus) Descriptor() ([]byte, []int) {
	return file_rpcproto_servicestatus_proto_rawDescGZIP(), []int{21}
}

func (x *PlayerMaxStatus) GetRegisterIsFull() bool {
	if x != nil {
		return x.RegisterIsFull
	}
	return false
}

func (x *PlayerMaxStatus) GetOnlineIsFull() bool {
	if x != nil {
		return x.OnlineIsFull
	}
	return false
}

var File_rpcproto_servicestatus_proto protoreflect.FileDescriptor

var file_rpcproto_servicestatus_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x70, 0x63, 0x22, 0x5a, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x57, 0x65, 0x69, 0x67, 0x68, 0x22,
	0x58, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x55,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x55, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x47, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x57, 0x65, 0x69, 0x67, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x57, 0x65, 0x69, 0x67, 0x68, 0x22, 0x68, 0x0a, 0x12, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x68, 0x0a, 0x16, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4f, 0x62, 0x6a, 0x4e, 0x75, 0x6d, 0x12, 0x2a,
	0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x7f, 0x0a, 0x17, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x47, 0x53, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47,
	0x53, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x64, 0x0a, 0x16, 0x4d,
	0x73, 0x67, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x42,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11,
	0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x32, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x41, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x61, 0x76, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x74, 0x49, 0x64, 0x22, 0x46, 0x0a,
	0x08, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x72, 0x65,
	0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x72, 0x65, 0x61, 0x49,
	0x64, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4e, 0x75, 0x6d, 0x22, 0x4d, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x37, 0x0a, 0x0f, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x18, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x3a, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x47, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5b,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x0e, 0x47, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x0e, 0x47, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x07, 0x43,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xc4,
	0x01, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x5c, 0x0a, 0x12, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x4d, 0x61,
	0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x1a, 0x53, 0x0a, 0x17, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x12, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x72, 0x65,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x0f, 0x41,
	0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x41,
	0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f,
	0x41, 0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x89, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x49, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x22, 0xc2, 0x01, 0x0a, 0x12,
	0x43, 0x61, 0x6c, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x12, 0x53, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x41, 0x72, 0x65, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0e, 0x4d, 0x61, 0x70, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x57, 0x0a, 0x13, 0x4d, 0x61, 0x70, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x5d, 0x0a, 0x0f, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x73, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x49, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x73, 0x46, 0x75, 0x6c, 0x6c, 0x42,
	0x07, 0x5a, 0x05, 0x2e, 0x3b, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcproto_servicestatus_proto_rawDescOnce sync.Once
	file_rpcproto_servicestatus_proto_rawDescData = file_rpcproto_servicestatus_proto_rawDesc
)

func file_rpcproto_servicestatus_proto_rawDescGZIP() []byte {
	file_rpcproto_servicestatus_proto_rawDescOnce.Do(func() {
		file_rpcproto_servicestatus_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcproto_servicestatus_proto_rawDescData)
	})
	return file_rpcproto_servicestatus_proto_rawDescData
}

var file_rpcproto_servicestatus_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_rpcproto_servicestatus_proto_goTypes = []interface{}{
	(*GameServiceBalance)(nil),       // 0: rpc.GameServiceBalance
	(*UpdatePlayerList)(nil),         // 1: rpc.UpdatePlayerList
	(*GateBalance)(nil),              // 2: rpc.GateBalance
	(*GateServiceConnect)(nil),       // 3: rpc.GateServiceConnect
	(*GameServicePlayerCount)(nil),   // 4: rpc.GameServicePlayerCount
	(*CenterServerBalanceInfo)(nil),  // 5: rpc.CenterServerBalanceInfo
	(*MsgCenterServerBalance)(nil),   // 6: rpc.MsgCenterServerBalance
	(*MsgAllServerNode)(nil),         // 7: rpc.MsgAllServerNode
	(*SaveAreaInfo)(nil),             // 8: rpc.SaveAreaInfo
	(*AreaInfo)(nil),                 // 9: rpc.AreaInfo
	(*GameInfo)(nil),                 // 10: rpc.GameInfo
	(*GetGameNodePlayerInfo)(nil),    // 11: rpc.GetGameNodePlayerInfo
	(*GameNodePlayerInfo)(nil),       // 12: rpc.GameNodePlayerInfo
	(*GameNodePlayerInfoResult)(nil), // 13: rpc.GameNodePlayerInfoResult
	(*GetGateServiceInfo)(nil),       // 14: rpc.GetGateServiceInfo
	(*GetGateServiceInfoResult)(nil), // 15: rpc.GetGateServiceInfoResult
	(*CallRet)(nil),                  // 16: rpc.CallRet
	(*ServiceNameInfo)(nil),          // 17: rpc.ServiceNameInfo
	(*CallAreaServiceReq)(nil),       // 18: rpc.CallAreaServiceReq
	(*CallAreaServiceInfo)(nil),      // 19: rpc.CallAreaServiceInfo
	(*CallAreaServiceRes)(nil),       // 20: rpc.CallAreaServiceRes
	(*PlayerMaxStatus)(nil),          // 21: rpc.PlayerMaxStatus
	nil,                              // 22: rpc.ServiceNameInfo.MapServiceNameInfoEntry
	nil,                              // 23: rpc.CallAreaServiceRes.MapServiceInfoEntry
}
var file_rpcproto_servicestatus_proto_depIdxs = []int32{
	5,  // 0: rpc.MsgCenterServerBalance.CenterBalanceList:type_name -> rpc.CenterServerBalanceInfo
	10, // 1: rpc.GameNodePlayerInfo.GameServiceInfo:type_name -> rpc.GameInfo
	11, // 2: rpc.GameNodePlayerInfoResult.ResultList:type_name -> rpc.GetGameNodePlayerInfo
	3,  // 3: rpc.GetGateServiceInfoResult.GateResultList:type_name -> rpc.GateServiceConnect
	22, // 4: rpc.ServiceNameInfo.MapServiceNameInfo:type_name -> rpc.ServiceNameInfo.MapServiceNameInfoEntry
	19, // 5: rpc.CallAreaServiceReq.AreaServiceInfo:type_name -> rpc.CallAreaServiceInfo
	23, // 6: rpc.CallAreaServiceRes.MapServiceInfo:type_name -> rpc.CallAreaServiceRes.MapServiceInfoEntry
	16, // 7: rpc.ServiceNameInfo.MapServiceNameInfoEntry.value:type_name -> rpc.CallRet
	17, // 8: rpc.CallAreaServiceRes.MapServiceInfoEntry.value:type_name -> rpc.ServiceNameInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpcproto_servicestatus_proto_init() }
func file_rpcproto_servicestatus_proto_init() {
	if File_rpcproto_servicestatus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcproto_servicestatus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServiceBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GateServiceConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServicePlayerCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CenterServerBalanceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgCenterServerBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAllServerNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveAreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameNodePlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameNodePlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameNodePlayerInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGateServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGateServiceInfoResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceNameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAreaServiceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAreaServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallAreaServiceRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcproto_servicestatus_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMaxStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcproto_servicestatus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpcproto_servicestatus_proto_goTypes,
		DependencyIndexes: file_rpcproto_servicestatus_proto_depIdxs,
		MessageInfos:      file_rpcproto_servicestatus_proto_msgTypes,
	}.Build()
	File_rpcproto_servicestatus_proto = out.File
	file_rpcproto_servicestatus_proto_rawDesc = nil
	file_rpcproto_servicestatus_proto_goTypes = nil
	file_rpcproto_servicestatus_proto_depIdxs = nil
}
