version: '3.8'  
services:  
  mongodb:  
    image: mongo:5 
    container_name: mongodb  
    restart: always  
    environment:  
      MONGO_INITDB_ROOT_USERNAME: admin  
      MONGO_INITDB_ROOT_PASSWORD: 123456  
    ports:  
      - "27017:27017"  
    volumes:  
      - mongodb_data:/mongodata/db
  
volumes:  
  mongodb_data: