nodes:
  - id: login-pub-1 # 本地公共 HTTP 登录节点。
    labels: {scope: pub} # 公共部署范围。
    allow_discovery:
      - services: [AccDBService] # 只发现公共账号数据服务。
        node_labels: {scope: pub}
    services: [LoginService]

  - id: gateway-pub-1 # 本地公共客户端长连接节点。
    labels: {scope: pub} # 公共部署范围。
    allow_discovery:
      - services: [AccDBService] # 玩家路由使用公共账号数据域。
        node_labels: {scope: pub}
      - services: [GameService] # Redis 返回精确节点后定向调用区服游戏服务。
        node_labels: {scope: area}
    services: [GatewayService]

  - id: db-pub-1 # 本地公共数据库节点。
    labels: {scope: pub} # 公共部署范围。
    allow_discovery: [] # DBService 首期不主动调用远端 Service。
    services:
      - "AccDBService:DBService" # DBService 模板的账号数据域实例。

  - id: game-area-1-1 # 真实区服 1 的第一个 Game 节点。
    labels: {scope: area, real_area_id: "1"} # 区服部署范围。
    allow_discovery:
      - services: [AccDBService, RoleDBService] # 只发现本区服 DB 节点上的两个数据域。
        node_labels: {scope: area, real_area_id: "1"}
    services: [GameService]

  - id: db-area-1-1 # 真实区服 1 的数据库节点。
    labels: {scope: area, real_area_id: "1"} # 区服部署范围。
    allow_discovery: [] # DBService 首期不主动调用远端 Service。
    services:
      - "AccDBService:DBService" # 公共登录协调数据域的区服内副本。
      - "RoleDBService:DBService" # 当前区服独立角色数据域。
