// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: messageid.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageID 是客户端与 Gateway 共同遵守的应用层消息编号。
type MessageID int32

const (
	MessageID_Ok                 MessageID = 0 // 成功且没有响应 Body 时使用。
	MessageID_LoginPlayerReq     MessageID = 1 // 客户端请求进入显示区服。
	MessageID_LoginPlayerRes     MessageID = 2 // 玩家登录成功数据或登录错误响应。
	MessageID_PlayerHeartbeatReq MessageID = 3 // 客户端玩家逻辑心跳。
	MessageID_PlayerKicked       MessageID = 4 // 玩家被其他连接顶号的主动推送。
)

// Enum value maps for MessageID.
var (
	MessageID_name = map[int32]string{
		0: "Ok",
		1: "LoginPlayerReq",
		2: "LoginPlayerRes",
		3: "PlayerHeartbeatReq",
		4: "PlayerKicked",
	}
	MessageID_value = map[string]int32{
		"Ok":                 0,
		"LoginPlayerReq":     1,
		"LoginPlayerRes":     2,
		"PlayerHeartbeatReq": 3,
		"PlayerKicked":       4,
	}
)

func (x MessageID) Enum() *MessageID {
	p := new(MessageID)
	*p = x
	return p
}

func (x MessageID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageID) Descriptor() protoreflect.EnumDescriptor {
	return file_messageid_proto_enumTypes[0].Descriptor()
}

func (MessageID) Type() protoreflect.EnumType {
	return &file_messageid_proto_enumTypes[0]
}

func (x MessageID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageID.Descriptor instead.
func (MessageID) EnumDescriptor() ([]byte, []int) {
	return file_messageid_proto_rawDescGZIP(), []int{0}
}

var File_messageid_proto protoreflect.FileDescriptor

var file_messageid_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0x65, 0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x44, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x6b, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12,
	0x12, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x4b, 0x69, 0x63, 0x6b, 0x65, 0x64, 0x10, 0x04, 0x42, 0x25, 0x5a,
	0x23, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageid_proto_rawDescOnce sync.Once
	file_messageid_proto_rawDescData = file_messageid_proto_rawDesc
)

func file_messageid_proto_rawDescGZIP() []byte {
	file_messageid_proto_rawDescOnce.Do(func() {
		file_messageid_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageid_proto_rawDescData)
	})
	return file_messageid_proto_rawDescData
}

var file_messageid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messageid_proto_goTypes = []interface{}{
	(MessageID)(0), // 0: origingame.protocol.MessageID
}
var file_messageid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageid_proto_init() }
func file_messageid_proto_init() {
	if File_messageid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageid_proto_goTypes,
		DependencyIndexes: file_messageid_proto_depIdxs,
		EnumInfos:         file_messageid_proto_enumTypes,
	}.Build()
	File_messageid_proto = out.File
	file_messageid_proto_rawDesc = nil
	file_messageid_proto_goTypes = nil
	file_messageid_proto_depIdxs = nil
}
