// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.24.0
// source: messageid.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageID 是客户端与 Gateway 共同遵守的应用层消息编号。
type MessageID int32

const (
	MessageID_Ok                 MessageID = 0 // 成功且没有响应 Body 时使用。
	MessageID_LoginPlayerReq     MessageID = 1 // 客户端请求进入显示区服。
	MessageID_LoginPlayerRes     MessageID = 2 // 玩家登录成功数据或登录错误响应。
	MessageID_PlayerHeartbeatReq MessageID = 3 // 客户端玩家逻辑心跳。
	MessageID_PlayerKicked       MessageID = 4 // 玩家被其他连接顶号的主动推送。
)

// Enum value maps for MessageID.
var (
	MessageID_name = map[int32]string{
		0: "Ok",
		1: "LoginPlayerReq",
		2: "LoginPlayerRes",
		3: "PlayerHeartbeatReq",
		4: "PlayerKicked",
	}
	MessageID_value = map[string]int32{
		"Ok":                 0,
		"LoginPlayerReq":     1,
		"LoginPlayerRes":     2,
		"PlayerHeartbeatReq": 3,
		"PlayerKicked":       4,
	}
)

func (x MessageID) Enum() *MessageID {
	p := new(MessageID)
	*p = x
	return p
}

func (x MessageID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageID) Descriptor() protoreflect.EnumDescriptor {
	return file_messageid_proto_enumTypes[0].Descriptor()
}

func (MessageID) Type() protoreflect.EnumType {
	return &file_messageid_proto_enumTypes[0]
}

func (x MessageID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageID.Descriptor instead.
func (MessageID) EnumDescriptor() ([]byte, []int) {
	return file_messageid_proto_rawDescGZIP(), []int{0}
}

var File_messageid_proto protoreflect.FileDescriptor

const file_messageid_proto_rawDesc = "" +
	"\n" +
	"\x0fmessageid.proto\x12\x13origingame.protocol*e\n" +
	"\tMessageID\x12\x06\n" +
	"\x02Ok\x10\x00\x12\x12\n" +
	"\x0eLoginPlayerReq\x10\x01\x12\x12\n" +
	"\x0eLoginPlayerRes\x10\x02\x12\x16\n" +
	"\x12PlayerHeartbeatReq\x10\x03\x12\x10\n" +
	"\fPlayerKicked\x10\x04B%Z#origingame/protocol/common;commonpbb\x06proto3"

var (
	file_messageid_proto_rawDescOnce sync.Once
	file_messageid_proto_rawDescData []byte
)

func file_messageid_proto_rawDescGZIP() []byte {
	file_messageid_proto_rawDescOnce.Do(func() {
		file_messageid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messageid_proto_rawDesc), len(file_messageid_proto_rawDesc)))
	})
	return file_messageid_proto_rawDescData
}

var file_messageid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messageid_proto_goTypes = []any{
	(MessageID)(0), // 0: origingame.protocol.MessageID
}
var file_messageid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageid_proto_init() }
func file_messageid_proto_init() {
	if File_messageid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messageid_proto_rawDesc), len(file_messageid_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messageid_proto_goTypes,
		DependencyIndexes: file_messageid_proto_depIdxs,
		EnumInfos:         file_messageid_proto_enumTypes,
	}.Build()
	File_messageid_proto = out.File
	file_messageid_proto_goTypes = nil
	file_messageid_proto_depIdxs = nil
}
