// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.24.0
// source: playerlogin.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginPlayerRequest 携带进入显示区服所需的客户端凭证。
type LoginPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                                // LoginService 签发的 JWT。
	ShowAreaId    int64                  `protobuf:"varint,2,opt,name=show_area_id,json=showAreaId,proto3" json:"show_area_id,omitempty"` // 客户端选择的显示区服 ID。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPlayerRequest) Reset() {
	*x = LoginPlayerRequest{}
	mi := &file_playerlogin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPlayerRequest) ProtoMessage() {}

func (x *LoginPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playerlogin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPlayerRequest.ProtoReflect.Descriptor instead.
func (*LoginPlayerRequest) Descriptor() ([]byte, []int) {
	return file_playerlogin_proto_rawDescGZIP(), []int{0}
}

func (x *LoginPlayerRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginPlayerRequest) GetShowAreaId() int64 {
	if x != nil {
		return x.ShowAreaId
	}
	return 0
}

// PlayerHeartbeatRequest 是玩家在线后的逻辑心跳，Body 没有业务字段。
type PlayerHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerHeartbeatRequest) Reset() {
	*x = PlayerHeartbeatRequest{}
	mi := &file_playerlogin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHeartbeatRequest) ProtoMessage() {}

func (x *PlayerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_playerlogin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*PlayerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_playerlogin_proto_rawDescGZIP(), []int{1}
}

// LoginPlayerResult 是玩家进入 GameService 成功后的客户端登录数据。
type LoginPlayerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleInfo      *RoleInfo              `protobuf:"bytes,1,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"` // 玩家常用公共基础数据。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginPlayerResult) Reset() {
	*x = LoginPlayerResult{}
	mi := &file_playerlogin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginPlayerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginPlayerResult) ProtoMessage() {}

func (x *LoginPlayerResult) ProtoReflect() protoreflect.Message {
	mi := &file_playerlogin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginPlayerResult.ProtoReflect.Descriptor instead.
func (*LoginPlayerResult) Descriptor() ([]byte, []int) {
	return file_playerlogin_proto_rawDescGZIP(), []int{2}
}

func (x *LoginPlayerResult) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

// RoleInfo 保存客户端经常使用的角色公共数据。
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`          // 账号 ID。
	ShowAreaId    int64                  `protobuf:"varint,2,opt,name=show_area_id,json=showAreaId,proto3" json:"show_area_id,omitempty"`    // 显示区服 ID。
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                             // 玩家昵称。
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                                  // 玩家等级。
	CreatedAtMs   int64                  `protobuf:"varint,5,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"` // 角色创建 Unix 毫秒时间。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_playerlogin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_playerlogin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_playerlogin_proto_rawDescGZIP(), []int{3}
}

func (x *RoleInfo) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RoleInfo) GetShowAreaId() int64 {
	if x != nil {
		return x.ShowAreaId
	}
	return 0
}

func (x *RoleInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RoleInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleInfo) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

// PlayerKickedNotify 通知客户端当前连接被其他登录替换。
type PlayerKickedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        ErrorCode              `protobuf:"varint,1,opt,name=reason,proto3,enum=origingame.protocol.ErrorCode" json:"reason,omitempty"` // 顶号时为 ERROR_CODE_GATEWAY_LOGGED_IN_ELSEWHERE。
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerKickedNotify) Reset() {
	*x = PlayerKickedNotify{}
	mi := &file_playerlogin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerKickedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerKickedNotify) ProtoMessage() {}

func (x *PlayerKickedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_playerlogin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerKickedNotify.ProtoReflect.Descriptor instead.
func (*PlayerKickedNotify) Descriptor() ([]byte, []int) {
	return file_playerlogin_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerKickedNotify) GetReason() ErrorCode {
	if x != nil {
		return x.Reason
	}
	return ErrorCode_ERROR_CODE_OK
}

var File_playerlogin_proto protoreflect.FileDescriptor

const file_playerlogin_proto_rawDesc = "" +
	"\n" +
	"\x11playerlogin.proto\x12\x13origingame.protocol\x1a\x0ferrorcode.proto\"L\n" +
	"\x12LoginPlayerRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12 \n" +
	"\fshow_area_id\x18\x02 \x01(\x03R\n" +
	"showAreaId\"\x18\n" +
	"\x16PlayerHeartbeatRequest\"O\n" +
	"\x11LoginPlayerResult\x12:\n" +
	"\trole_info\x18\x01 \x01(\v2\x1d.origingame.protocol.RoleInfoR\broleInfo\"\xa1\x01\n" +
	"\bRoleInfo\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12 \n" +
	"\fshow_area_id\x18\x02 \x01(\x03R\n" +
	"showAreaId\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\"\n" +
	"\rcreated_at_ms\x18\x05 \x01(\x03R\vcreatedAtMs\"L\n" +
	"\x12PlayerKickedNotify\x126\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x1e.origingame.protocol.ErrorCodeR\x06reasonB%Z#origingame/protocol/common;commonpbb\x06proto3"

var (
	file_playerlogin_proto_rawDescOnce sync.Once
	file_playerlogin_proto_rawDescData []byte
)

func file_playerlogin_proto_rawDescGZIP() []byte {
	file_playerlogin_proto_rawDescOnce.Do(func() {
		file_playerlogin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playerlogin_proto_rawDesc), len(file_playerlogin_proto_rawDesc)))
	})
	return file_playerlogin_proto_rawDescData
}

var file_playerlogin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_playerlogin_proto_goTypes = []any{
	(*LoginPlayerRequest)(nil),     // 0: origingame.protocol.LoginPlayerRequest
	(*PlayerHeartbeatRequest)(nil), // 1: origingame.protocol.PlayerHeartbeatRequest
	(*LoginPlayerResult)(nil),      // 2: origingame.protocol.LoginPlayerResult
	(*RoleInfo)(nil),               // 3: origingame.protocol.RoleInfo
	(*PlayerKickedNotify)(nil),     // 4: origingame.protocol.PlayerKickedNotify
	(ErrorCode)(0),                 // 5: origingame.protocol.ErrorCode
}
var file_playerlogin_proto_depIdxs = []int32{
	3, // 0: origingame.protocol.LoginPlayerResult.role_info:type_name -> origingame.protocol.RoleInfo
	5, // 1: origingame.protocol.PlayerKickedNotify.reason:type_name -> origingame.protocol.ErrorCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_playerlogin_proto_init() }
func file_playerlogin_proto_init() {
	if File_playerlogin_proto != nil {
		return
	}
	file_errorcode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playerlogin_proto_rawDesc), len(file_playerlogin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playerlogin_proto_goTypes,
		DependencyIndexes: file_playerlogin_proto_depIdxs,
		MessageInfos:      file_playerlogin_proto_msgTypes,
	}.Build()
	File_playerlogin_proto = out.File
	file_playerlogin_proto_goTypes = nil
	file_playerlogin_proto_depIdxs = nil
}
