// Code generated by origingen rpc; DO NOT EDIT.

package rpcapi

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const dBServiceContractID rpc.ContractID = 0x5ac3c56fa2092fe3

var dBServiceFingerprint = rpc.ContractFingerprint{0xbd, 0xeb, 0xf0, 0xaa, 0x4f, 0x8f, 0x51, 0x49, 0x58, 0xb3, 0xd8, 0x8a, 0x4c, 0x27, 0x76, 0xf4, 0xb8, 0xe6, 0xfd, 0x49, 0x6f, 0xfa, 0x9d, 0x7f, 0x68, 0x39, 0x56, 0x0c, 0x5c, 0xbc, 0x5b, 0x75}

const dBServiceExecuteMongoMethodID rpc.MethodID = 0xa20b17187db858bc
const dBServiceExecuteRedisMethodID rpc.MethodID = 0xfee5f4f1673a7653

// DBServiceClient 是 origingame/protocol/rpc.DBService 的强类型生成客户端。
type DBServiceClient struct {
	client rpc.Client
}

// NewDBServiceClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewDBServiceClient(owner service.IService, target rpc.Target) DBServiceClient {
	return DBServiceClient{client: rpc.NewGeneratedClient(owner, target, dBServiceContractID, dBServiceFingerprint)}
}

// BindDBService 使用契约默认 ServiceName "DBService" 绑定轻量客户端。
func BindDBService(owner service.IService) DBServiceClient {
	return NewDBServiceClient(owner, rpc.ToService("DBService"))
}

// BindDBServiceTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindDBServiceTo(owner service.IService, serviceName string) DBServiceClient {
	return NewDBServiceClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client DBServiceClient) OnNode(nodeID string) DBServiceClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// WhereLabels 派生按 Node Labels 精确筛选候选的客户端。
func (client DBServiceClient) WhereLabels(labels map[string]string) DBServiceClient {
	client.client = client.client.WhereLabels(labels)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client DBServiceClient) RouteRoundRobin() DBServiceClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client DBServiceClient) RouteRandom() DBServiceClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client DBServiceClient) Route(key any) DBServiceClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client DBServiceClient) RouteBy(selector rpc.RouteSelector) DBServiceClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client DBServiceClient) IncludeRetired() DBServiceClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodeDBServiceExecuteMongoRequest 计算并一次写入当前方法请求载荷。
func encodeDBServiceExecuteMongoRequest(client rpc.Client, kind rpc.CallKind, arg1 MongoRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.DispatchKey)); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.AddContainer(len(arg1.Operations), arg1.Operations == nil); err != nil {
		return nil, err
	}
	for index1 := range arg1.Operations {
		_ = index1
		if err := sizer.Add(4); err != nil {
			return nil, err
		}
		if err := sizer.AddString(string(arg1.Operations[index1].Collection)); err != nil {
			return nil, err
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].Expectation != nil {
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Documents != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Inserted != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Matched != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Modified != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Deleted != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if (*arg1.Operations[index1].Expectation).Upserted != nil {
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
				if err := sizer.Add(8); err != nil {
					return nil, err
				}
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].InsertOne != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].InsertOne).Document)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].InsertMany != nil {
			if err := sizer.AddContainer(len((*arg1.Operations[index1].InsertMany).Documents), (*arg1.Operations[index1].InsertMany).Documents == nil); err != nil {
				return nil, err
			}
			for index2 := range (*arg1.Operations[index1].InsertMany).Documents {
				_ = index2
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].InsertMany).Documents[index2])); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].FindOne != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOne).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOne).Projection)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOne).Sort)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].FindMany != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindMany).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindMany).Projection)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindMany).Sort)); err != nil {
				return nil, err
			}
			if err := sizer.Add(8); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].CountDocuments != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].CountDocuments).Filter)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].EstimatedDocumentCount != nil {
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].Aggregate != nil {
			if err := sizer.AddContainer(len((*arg1.Operations[index1].Aggregate).Pipeline), (*arg1.Operations[index1].Aggregate).Pipeline == nil); err != nil {
				return nil, err
			}
			for index3 := range (*arg1.Operations[index1].Aggregate).Pipeline {
				_ = index3
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].Aggregate).Pipeline[index3])); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(8); err != nil {
				return nil, err
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].UpdateOne != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateOne).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.Add(4); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateOne).Update.Document)); err != nil {
				return nil, err
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].UpdateOne).Update.Pipeline), (*arg1.Operations[index1].UpdateOne).Update.Pipeline == nil); err != nil {
				return nil, err
			}
			for index4 := range (*arg1.Operations[index1].UpdateOne).Update.Pipeline {
				_ = index4
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateOne).Update.Pipeline[index4])); err != nil {
					return nil, err
				}
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].UpdateOne).ArrayFilters), (*arg1.Operations[index1].UpdateOne).ArrayFilters == nil); err != nil {
				return nil, err
			}
			for index5 := range (*arg1.Operations[index1].UpdateOne).ArrayFilters {
				_ = index5
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateOne).ArrayFilters[index5])); err != nil {
					return nil, err
				}
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].UpdateMany != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateMany).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.Add(4); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateMany).Update.Document)); err != nil {
				return nil, err
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].UpdateMany).Update.Pipeline), (*arg1.Operations[index1].UpdateMany).Update.Pipeline == nil); err != nil {
				return nil, err
			}
			for index6 := range (*arg1.Operations[index1].UpdateMany).Update.Pipeline {
				_ = index6
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateMany).Update.Pipeline[index6])); err != nil {
					return nil, err
				}
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].UpdateMany).ArrayFilters), (*arg1.Operations[index1].UpdateMany).ArrayFilters == nil); err != nil {
				return nil, err
			}
			for index7 := range (*arg1.Operations[index1].UpdateMany).ArrayFilters {
				_ = index7
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].UpdateMany).ArrayFilters[index7])); err != nil {
					return nil, err
				}
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].ReplaceOne != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].ReplaceOne).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].ReplaceOne).Replacement)); err != nil {
				return nil, err
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].FindOneAndUpdate != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.Add(4); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).Update.Document)); err != nil {
				return nil, err
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].FindOneAndUpdate).Update.Pipeline), (*arg1.Operations[index1].FindOneAndUpdate).Update.Pipeline == nil); err != nil {
				return nil, err
			}
			for index8 := range (*arg1.Operations[index1].FindOneAndUpdate).Update.Pipeline {
				_ = index8
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).Update.Pipeline[index8])); err != nil {
					return nil, err
				}
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).Projection)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).Sort)); err != nil {
				return nil, err
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if err := sizer.Add(4); err != nil {
				return nil, err
			}
			if err := sizer.AddContainer(len((*arg1.Operations[index1].FindOneAndUpdate).ArrayFilters), (*arg1.Operations[index1].FindOneAndUpdate).ArrayFilters == nil); err != nil {
				return nil, err
			}
			for index9 := range (*arg1.Operations[index1].FindOneAndUpdate).ArrayFilters {
				_ = index9
				if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndUpdate).ArrayFilters[index9])); err != nil {
					return nil, err
				}
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].FindOneAndReplace != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndReplace).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndReplace).Replacement)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndReplace).Projection)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndReplace).Sort)); err != nil {
				return nil, err
			}
			if err := sizer.Add(1); err != nil {
				return nil, err
			}
			if err := sizer.Add(4); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].FindOneAndDelete != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndDelete).Filter)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndDelete).Projection)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].FindOneAndDelete).Sort)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].DeleteOne != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].DeleteOne).Filter)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].DeleteMany != nil {
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].DeleteMany).Filter)); err != nil {
				return nil, err
			}
		}
		if err := sizer.Add(1); err != nil {
			return nil, err
		}
		if arg1.Operations[index1].RawCommand != nil {
			if err := sizer.AddString(string((*arg1.Operations[index1].RawCommand).ID)); err != nil {
				return nil, err
			}
			if err := sizer.AddBytes([]byte((*arg1.Operations[index1].RawCommand).Command)); err != nil {
				return nil, err
			}
			if err := sizer.Add(8); err != nil {
				return nil, err
			}
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.DispatchKey)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt32(int32(arg1.ExecuteMode)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteContainer(len(arg1.Operations), arg1.Operations == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index10 := range arg1.Operations {
		if err := writer.WriteInt32(int32(arg1.Operations[index10].Kind)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WriteString(string(arg1.Operations[index10].Collection)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WritePresence(arg1.Operations[index10].Expectation != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].Expectation != nil {
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Documents != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Documents != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Documents).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Documents).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Inserted != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Inserted != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Inserted).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Inserted).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Matched != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Matched != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Matched).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Matched).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Modified != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Modified != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Modified).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Modified).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Deleted != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Deleted != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Deleted).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Deleted).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WritePresence((*arg1.Operations[index10].Expectation).Upserted != nil); err != nil {
				buffer.Release()
				return nil, err
			}
			if (*arg1.Operations[index10].Expectation).Upserted != nil {
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Upserted).Min)); err != nil {
					buffer.Release()
					return nil, err
				}
				if err := writer.WriteInt64(int64((*(*arg1.Operations[index10].Expectation).Upserted).Max)); err != nil {
					buffer.Release()
					return nil, err
				}
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].InsertOne != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].InsertOne != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].InsertOne).Document)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].InsertMany != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].InsertMany != nil {
			if err := writer.WriteContainer(len((*arg1.Operations[index10].InsertMany).Documents), (*arg1.Operations[index10].InsertMany).Documents == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index11 := range (*arg1.Operations[index10].InsertMany).Documents {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].InsertMany).Documents[index11])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].InsertMany).Unordered)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].FindOne != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].FindOne != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOne).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOne).Projection)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOne).Sort)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].FindMany != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].FindMany != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindMany).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindMany).Projection)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindMany).Sort)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt64(int64((*arg1.Operations[index10].FindMany).Limit)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].CountDocuments != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].CountDocuments != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].CountDocuments).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].EstimatedDocumentCount != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].EstimatedDocumentCount != nil {
			if err := writer.WriteBool(bool((*arg1.Operations[index10].EstimatedDocumentCount))); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].Aggregate != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].Aggregate != nil {
			if err := writer.WriteContainer(len((*arg1.Operations[index10].Aggregate).Pipeline), (*arg1.Operations[index10].Aggregate).Pipeline == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index12 := range (*arg1.Operations[index10].Aggregate).Pipeline {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].Aggregate).Pipeline[index12])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WriteInt64(int64((*arg1.Operations[index10].Aggregate).MaxDocuments)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].Aggregate).AllowDiskUse)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].UpdateOne != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].UpdateOne != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateOne).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt32(int32((*arg1.Operations[index10].UpdateOne).Update.Kind)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateOne).Update.Document)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].UpdateOne).Update.Pipeline), (*arg1.Operations[index10].UpdateOne).Update.Pipeline == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index13 := range (*arg1.Operations[index10].UpdateOne).Update.Pipeline {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateOne).Update.Pipeline[index13])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].UpdateOne).Upsert)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].UpdateOne).ArrayFilters), (*arg1.Operations[index10].UpdateOne).ArrayFilters == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index14 := range (*arg1.Operations[index10].UpdateOne).ArrayFilters {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateOne).ArrayFilters[index14])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].UpdateMany != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].UpdateMany != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateMany).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt32(int32((*arg1.Operations[index10].UpdateMany).Update.Kind)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateMany).Update.Document)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].UpdateMany).Update.Pipeline), (*arg1.Operations[index10].UpdateMany).Update.Pipeline == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index15 := range (*arg1.Operations[index10].UpdateMany).Update.Pipeline {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateMany).Update.Pipeline[index15])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].UpdateMany).ArrayFilters), (*arg1.Operations[index10].UpdateMany).ArrayFilters == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index16 := range (*arg1.Operations[index10].UpdateMany).ArrayFilters {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].UpdateMany).ArrayFilters[index16])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].ReplaceOne != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].ReplaceOne != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].ReplaceOne).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].ReplaceOne).Replacement)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].ReplaceOne).Upsert)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].FindOneAndUpdate != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].FindOneAndUpdate != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt32(int32((*arg1.Operations[index10].FindOneAndUpdate).Update.Kind)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).Update.Document)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].FindOneAndUpdate).Update.Pipeline), (*arg1.Operations[index10].FindOneAndUpdate).Update.Pipeline == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index17 := range (*arg1.Operations[index10].FindOneAndUpdate).Update.Pipeline {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).Update.Pipeline[index17])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).Projection)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).Sort)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].FindOneAndUpdate).Upsert)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt32(int32((*arg1.Operations[index10].FindOneAndUpdate).ReturnDocument)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteContainer(len((*arg1.Operations[index10].FindOneAndUpdate).ArrayFilters), (*arg1.Operations[index10].FindOneAndUpdate).ArrayFilters == nil); err != nil {
				buffer.Release()
				return nil, err
			}
			for index18 := range (*arg1.Operations[index10].FindOneAndUpdate).ArrayFilters {
				if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndUpdate).ArrayFilters[index18])); err != nil {
					buffer.Release()
					return nil, err
				}
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].FindOneAndReplace != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].FindOneAndReplace != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndReplace).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndReplace).Replacement)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndReplace).Projection)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndReplace).Sort)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBool(bool((*arg1.Operations[index10].FindOneAndReplace).Upsert)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt32(int32((*arg1.Operations[index10].FindOneAndReplace).ReturnDocument)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].FindOneAndDelete != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].FindOneAndDelete != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndDelete).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndDelete).Projection)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].FindOneAndDelete).Sort)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].DeleteOne != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].DeleteOne != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].DeleteOne).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].DeleteMany != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].DeleteMany != nil {
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].DeleteMany).Filter)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WritePresence(arg1.Operations[index10].RawCommand != nil); err != nil {
			buffer.Release()
			return nil, err
		}
		if arg1.Operations[index10].RawCommand != nil {
			if err := writer.WriteString(string((*arg1.Operations[index10].RawCommand).ID)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteBytes([]byte((*arg1.Operations[index10].RawCommand).Command)); err != nil {
				buffer.Release()
				return nil, err
			}
			if err := writer.WriteInt64(int64((*arg1.Operations[index10].RawCommand).MaxDocuments)); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeDBServiceExecuteMongoRequest 按固定契约顺序解码并校验完整载荷。
func decodeDBServiceExecuteMongoRequest(data []byte) (arg1 MongoRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.DispatchKey = string(decoded1)
	var decoded2 int32
	decoded2, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.ExecuteMode = MongoExecuteMode(decoded2)
	var length3 int
	var isNil4 bool
	length3, isNil4, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length3, 25)
	if decodeErr != nil {
		return
	}
	if !isNil4 {
		arg1.Operations = make([]MongoOperation, length3)
		for index5 := 0; index5 < length3; index5++ {
			var decoded6 int32
			decoded6, decodeErr = reader.ReadInt32()
			if decodeErr != nil {
				return
			}
			arg1.Operations[index5].Kind = MongoOperationKind(decoded6)
			var decoded7 string
			decoded7, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg1.Operations[index5].Collection = string(decoded7)
			var present8 bool
			present8, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present8 {
				arg1.Operations[index5].Expectation = (*MongoExpectation)(new(MongoExpectation))
				var present9 bool
				present9, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present9 {
					(*arg1.Operations[index5].Expectation).Documents = (*MongoCountRange)(new(MongoCountRange))
					var decoded10 int64
					decoded10, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Documents).Min = int64(decoded10)
					var decoded11 int64
					decoded11, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Documents).Max = int64(decoded11)
				}
				var present12 bool
				present12, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present12 {
					(*arg1.Operations[index5].Expectation).Inserted = (*MongoCountRange)(new(MongoCountRange))
					var decoded13 int64
					decoded13, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Inserted).Min = int64(decoded13)
					var decoded14 int64
					decoded14, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Inserted).Max = int64(decoded14)
				}
				var present15 bool
				present15, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present15 {
					(*arg1.Operations[index5].Expectation).Matched = (*MongoCountRange)(new(MongoCountRange))
					var decoded16 int64
					decoded16, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Matched).Min = int64(decoded16)
					var decoded17 int64
					decoded17, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Matched).Max = int64(decoded17)
				}
				var present18 bool
				present18, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present18 {
					(*arg1.Operations[index5].Expectation).Modified = (*MongoCountRange)(new(MongoCountRange))
					var decoded19 int64
					decoded19, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Modified).Min = int64(decoded19)
					var decoded20 int64
					decoded20, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Modified).Max = int64(decoded20)
				}
				var present21 bool
				present21, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present21 {
					(*arg1.Operations[index5].Expectation).Deleted = (*MongoCountRange)(new(MongoCountRange))
					var decoded22 int64
					decoded22, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Deleted).Min = int64(decoded22)
					var decoded23 int64
					decoded23, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Deleted).Max = int64(decoded23)
				}
				var present24 bool
				present24, decodeErr = reader.ReadPresence()
				if decodeErr != nil {
					return
				}
				if present24 {
					(*arg1.Operations[index5].Expectation).Upserted = (*MongoCountRange)(new(MongoCountRange))
					var decoded25 int64
					decoded25, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Upserted).Min = int64(decoded25)
					var decoded26 int64
					decoded26, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					(*(*arg1.Operations[index5].Expectation).Upserted).Max = int64(decoded26)
				}
			}
			var present27 bool
			present27, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present27 {
				arg1.Operations[index5].InsertOne = (*MongoInsertOne)(new(MongoInsertOne))
				var decoded28 []byte
				decoded28, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].InsertOne).Document = []byte(decoded28)
			}
			var present29 bool
			present29, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present29 {
				arg1.Operations[index5].InsertMany = (*MongoInsertMany)(new(MongoInsertMany))
				var length30 int
				var isNil31 bool
				length30, isNil31, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length30, 4)
				if decodeErr != nil {
					return
				}
				if !isNil31 {
					(*arg1.Operations[index5].InsertMany).Documents = make([][]byte, length30)
					for index32 := 0; index32 < length30; index32++ {
						var decoded33 []byte
						decoded33, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].InsertMany).Documents[index32] = []byte(decoded33)
					}
				}
				var decoded34 bool
				decoded34, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].InsertMany).Unordered = bool(decoded34)
			}
			var present35 bool
			present35, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present35 {
				arg1.Operations[index5].FindOne = (*MongoFindOne)(new(MongoFindOne))
				var decoded36 []byte
				decoded36, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOne).Filter = []byte(decoded36)
				var decoded37 []byte
				decoded37, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOne).Projection = []byte(decoded37)
				var decoded38 []byte
				decoded38, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOne).Sort = []byte(decoded38)
			}
			var present39 bool
			present39, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present39 {
				arg1.Operations[index5].FindMany = (*MongoFindMany)(new(MongoFindMany))
				var decoded40 []byte
				decoded40, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindMany).Filter = []byte(decoded40)
				var decoded41 []byte
				decoded41, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindMany).Projection = []byte(decoded41)
				var decoded42 []byte
				decoded42, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindMany).Sort = []byte(decoded42)
				var decoded43 int64
				decoded43, decodeErr = reader.ReadInt64()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindMany).Limit = int64(decoded43)
			}
			var present44 bool
			present44, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present44 {
				arg1.Operations[index5].CountDocuments = (*MongoCountDocuments)(new(MongoCountDocuments))
				var decoded45 []byte
				decoded45, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].CountDocuments).Filter = []byte(decoded45)
			}
			var present46 bool
			present46, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present46 {
				arg1.Operations[index5].EstimatedDocumentCount = (*MongoEstimatedDocumentCount)(new(MongoEstimatedDocumentCount))
				var decoded47 bool
				decoded47, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].EstimatedDocumentCount) = MongoEstimatedDocumentCount(decoded47)
			}
			var present48 bool
			present48, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present48 {
				arg1.Operations[index5].Aggregate = (*MongoAggregate)(new(MongoAggregate))
				var length49 int
				var isNil50 bool
				length49, isNil50, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length49, 4)
				if decodeErr != nil {
					return
				}
				if !isNil50 {
					(*arg1.Operations[index5].Aggregate).Pipeline = make([][]byte, length49)
					for index51 := 0; index51 < length49; index51++ {
						var decoded52 []byte
						decoded52, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].Aggregate).Pipeline[index51] = []byte(decoded52)
					}
				}
				var decoded53 int64
				decoded53, decodeErr = reader.ReadInt64()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].Aggregate).MaxDocuments = int64(decoded53)
				var decoded54 bool
				decoded54, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].Aggregate).AllowDiskUse = bool(decoded54)
			}
			var present55 bool
			present55, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present55 {
				arg1.Operations[index5].UpdateOne = (*MongoUpdateOne)(new(MongoUpdateOne))
				var decoded56 []byte
				decoded56, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateOne).Filter = []byte(decoded56)
				var decoded57 int32
				decoded57, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateOne).Update.Kind = MongoUpdateKind(decoded57)
				var decoded58 []byte
				decoded58, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateOne).Update.Document = []byte(decoded58)
				var length59 int
				var isNil60 bool
				length59, isNil60, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length59, 4)
				if decodeErr != nil {
					return
				}
				if !isNil60 {
					(*arg1.Operations[index5].UpdateOne).Update.Pipeline = make([][]byte, length59)
					for index61 := 0; index61 < length59; index61++ {
						var decoded62 []byte
						decoded62, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].UpdateOne).Update.Pipeline[index61] = []byte(decoded62)
					}
				}
				var decoded63 bool
				decoded63, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateOne).Upsert = bool(decoded63)
				var length64 int
				var isNil65 bool
				length64, isNil65, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length64, 4)
				if decodeErr != nil {
					return
				}
				if !isNil65 {
					(*arg1.Operations[index5].UpdateOne).ArrayFilters = make([][]byte, length64)
					for index66 := 0; index66 < length64; index66++ {
						var decoded67 []byte
						decoded67, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].UpdateOne).ArrayFilters[index66] = []byte(decoded67)
					}
				}
			}
			var present68 bool
			present68, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present68 {
				arg1.Operations[index5].UpdateMany = (*MongoUpdateMany)(new(MongoUpdateMany))
				var decoded69 []byte
				decoded69, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateMany).Filter = []byte(decoded69)
				var decoded70 int32
				decoded70, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateMany).Update.Kind = MongoUpdateKind(decoded70)
				var decoded71 []byte
				decoded71, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].UpdateMany).Update.Document = []byte(decoded71)
				var length72 int
				var isNil73 bool
				length72, isNil73, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length72, 4)
				if decodeErr != nil {
					return
				}
				if !isNil73 {
					(*arg1.Operations[index5].UpdateMany).Update.Pipeline = make([][]byte, length72)
					for index74 := 0; index74 < length72; index74++ {
						var decoded75 []byte
						decoded75, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].UpdateMany).Update.Pipeline[index74] = []byte(decoded75)
					}
				}
				var length76 int
				var isNil77 bool
				length76, isNil77, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length76, 4)
				if decodeErr != nil {
					return
				}
				if !isNil77 {
					(*arg1.Operations[index5].UpdateMany).ArrayFilters = make([][]byte, length76)
					for index78 := 0; index78 < length76; index78++ {
						var decoded79 []byte
						decoded79, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].UpdateMany).ArrayFilters[index78] = []byte(decoded79)
					}
				}
			}
			var present80 bool
			present80, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present80 {
				arg1.Operations[index5].ReplaceOne = (*MongoReplaceOne)(new(MongoReplaceOne))
				var decoded81 []byte
				decoded81, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].ReplaceOne).Filter = []byte(decoded81)
				var decoded82 []byte
				decoded82, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].ReplaceOne).Replacement = []byte(decoded82)
				var decoded83 bool
				decoded83, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].ReplaceOne).Upsert = bool(decoded83)
			}
			var present84 bool
			present84, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present84 {
				arg1.Operations[index5].FindOneAndUpdate = (*MongoFindOneAndUpdate)(new(MongoFindOneAndUpdate))
				var decoded85 []byte
				decoded85, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Filter = []byte(decoded85)
				var decoded86 int32
				decoded86, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Update.Kind = MongoUpdateKind(decoded86)
				var decoded87 []byte
				decoded87, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Update.Document = []byte(decoded87)
				var length88 int
				var isNil89 bool
				length88, isNil89, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length88, 4)
				if decodeErr != nil {
					return
				}
				if !isNil89 {
					(*arg1.Operations[index5].FindOneAndUpdate).Update.Pipeline = make([][]byte, length88)
					for index90 := 0; index90 < length88; index90++ {
						var decoded91 []byte
						decoded91, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].FindOneAndUpdate).Update.Pipeline[index90] = []byte(decoded91)
					}
				}
				var decoded92 []byte
				decoded92, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Projection = []byte(decoded92)
				var decoded93 []byte
				decoded93, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Sort = []byte(decoded93)
				var decoded94 bool
				decoded94, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).Upsert = bool(decoded94)
				var decoded95 int32
				decoded95, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndUpdate).ReturnDocument = MongoReturnDocument(decoded95)
				var length96 int
				var isNil97 bool
				length96, isNil97, decodeErr = reader.ReadContainer()
				if decodeErr != nil {
					return
				}
				decodeErr = reader.CheckElements(length96, 4)
				if decodeErr != nil {
					return
				}
				if !isNil97 {
					(*arg1.Operations[index5].FindOneAndUpdate).ArrayFilters = make([][]byte, length96)
					for index98 := 0; index98 < length96; index98++ {
						var decoded99 []byte
						decoded99, decodeErr = reader.ReadBytes()
						if decodeErr != nil {
							return
						}
						(*arg1.Operations[index5].FindOneAndUpdate).ArrayFilters[index98] = []byte(decoded99)
					}
				}
			}
			var present100 bool
			present100, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present100 {
				arg1.Operations[index5].FindOneAndReplace = (*MongoFindOneAndReplace)(new(MongoFindOneAndReplace))
				var decoded101 []byte
				decoded101, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).Filter = []byte(decoded101)
				var decoded102 []byte
				decoded102, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).Replacement = []byte(decoded102)
				var decoded103 []byte
				decoded103, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).Projection = []byte(decoded103)
				var decoded104 []byte
				decoded104, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).Sort = []byte(decoded104)
				var decoded105 bool
				decoded105, decodeErr = reader.ReadBool()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).Upsert = bool(decoded105)
				var decoded106 int32
				decoded106, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndReplace).ReturnDocument = MongoReturnDocument(decoded106)
			}
			var present107 bool
			present107, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present107 {
				arg1.Operations[index5].FindOneAndDelete = (*MongoFindOneAndDelete)(new(MongoFindOneAndDelete))
				var decoded108 []byte
				decoded108, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndDelete).Filter = []byte(decoded108)
				var decoded109 []byte
				decoded109, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndDelete).Projection = []byte(decoded109)
				var decoded110 []byte
				decoded110, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].FindOneAndDelete).Sort = []byte(decoded110)
			}
			var present111 bool
			present111, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present111 {
				arg1.Operations[index5].DeleteOne = (*MongoDeleteOne)(new(MongoDeleteOne))
				var decoded112 []byte
				decoded112, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].DeleteOne).Filter = []byte(decoded112)
			}
			var present113 bool
			present113, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present113 {
				arg1.Operations[index5].DeleteMany = (*MongoDeleteMany)(new(MongoDeleteMany))
				var decoded114 []byte
				decoded114, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].DeleteMany).Filter = []byte(decoded114)
			}
			var present115 bool
			present115, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present115 {
				arg1.Operations[index5].RawCommand = (*MongoRawCommand)(new(MongoRawCommand))
				var decoded116 string
				decoded116, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].RawCommand).ID = string(decoded116)
				var decoded117 []byte
				decoded117, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].RawCommand).Command = []byte(decoded117)
				var decoded118 int64
				decoded118, decodeErr = reader.ReadInt64()
				if decodeErr != nil {
					return
				}
				(*arg1.Operations[index5].RawCommand).MaxDocuments = int64(decoded118)
			}
		}
	}
	decodeErr = reader.Done()
	return
}

// encodeDBServiceExecuteMongoResponse 计算并一次写入当前方法响应载荷。
func encodeDBServiceExecuteMongoResponse(response *rpc.ResponseWriter, result1 MongoResult) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddContainer(len(result1.Results), result1.Results == nil); err != nil {
		return err
	}
	for index1 := range result1.Results {
		_ = index1
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.AddContainer(len(result1.Results[index1].Documents), result1.Results[index1].Documents == nil); err != nil {
			return err
		}
		for index2 := range result1.Results[index1].Documents {
			_ = index2
			if err := sizer.AddBytes([]byte(result1.Results[index1].Documents[index2])); err != nil {
				return err
			}
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.AddContainer(len(result1.Results[index1].InsertedIDs), result1.Results[index1].InsertedIDs == nil); err != nil {
			return err
		}
		for index3 := range result1.Results[index1].InsertedIDs {
			_ = index3
			if err := sizer.Add(1); err != nil {
				return err
			}
			if err := sizer.AddBytes([]byte(result1.Results[index1].InsertedIDs[index3].Value)); err != nil {
				return err
			}
		}
		if err := sizer.AddContainer(len(result1.Results[index1].UpsertedIDs), result1.Results[index1].UpsertedIDs == nil); err != nil {
			return err
		}
		for index4 := range result1.Results[index1].UpsertedIDs {
			_ = index4
			if err := sizer.Add(1); err != nil {
				return err
			}
			if err := sizer.AddBytes([]byte(result1.Results[index1].UpsertedIDs[index4].Value)); err != nil {
				return err
			}
		}
		if err := sizer.AddContainer(len(result1.Results[index1].WriteFailures), result1.Results[index1].WriteFailures == nil); err != nil {
			return err
		}
		for index5 := range result1.Results[index1].WriteFailures {
			_ = index5
			if err := sizer.Add(4); err != nil {
				return err
			}
			if err := sizer.Add(4); err != nil {
				return err
			}
			if err := sizer.Add(4); err != nil {
				return err
			}
		}
		if err := sizer.AddBytes([]byte(result1.Results[index1].CommandResponse)); err != nil {
			return err
		}
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if result1.Failure != nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteContainer(len(result1.Results), result1.Results == nil); err != nil {
		return err
	}
	for index6 := range result1.Results {
		if err := writer.WriteInt32(int32(result1.Results[index6].Status)); err != nil {
			return err
		}
		if err := writer.WriteContainer(len(result1.Results[index6].Documents), result1.Results[index6].Documents == nil); err != nil {
			return err
		}
		for index7 := range result1.Results[index6].Documents {
			if err := writer.WriteBytes([]byte(result1.Results[index6].Documents[index7])); err != nil {
				return err
			}
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].Count)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].InsertedCount)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].MatchedCount)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].ModifiedCount)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].DeletedCount)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Results[index6].UpsertedCount)); err != nil {
			return err
		}
		if err := writer.WriteContainer(len(result1.Results[index6].InsertedIDs), result1.Results[index6].InsertedIDs == nil); err != nil {
			return err
		}
		for index8 := range result1.Results[index6].InsertedIDs {
			if err := writer.WriteUint8(uint8(result1.Results[index6].InsertedIDs[index8].Type)); err != nil {
				return err
			}
			if err := writer.WriteBytes([]byte(result1.Results[index6].InsertedIDs[index8].Value)); err != nil {
				return err
			}
		}
		if err := writer.WriteContainer(len(result1.Results[index6].UpsertedIDs), result1.Results[index6].UpsertedIDs == nil); err != nil {
			return err
		}
		for index9 := range result1.Results[index6].UpsertedIDs {
			if err := writer.WriteUint8(uint8(result1.Results[index6].UpsertedIDs[index9].Type)); err != nil {
				return err
			}
			if err := writer.WriteBytes([]byte(result1.Results[index6].UpsertedIDs[index9].Value)); err != nil {
				return err
			}
		}
		if err := writer.WriteContainer(len(result1.Results[index6].WriteFailures), result1.Results[index6].WriteFailures == nil); err != nil {
			return err
		}
		for index10 := range result1.Results[index6].WriteFailures {
			if err := writer.WriteInt32(int32(result1.Results[index6].WriteFailures[index10].DocumentIndex)); err != nil {
				return err
			}
			if err := writer.WriteInt32(int32(result1.Results[index6].WriteFailures[index10].Kind)); err != nil {
				return err
			}
			if err := writer.WriteInt32(int32(result1.Results[index6].WriteFailures[index10].ServerCode)); err != nil {
				return err
			}
		}
		if err := writer.WriteBytes([]byte(result1.Results[index6].CommandResponse)); err != nil {
			return err
		}
	}
	if err := writer.WritePresence(result1.Failure != nil); err != nil {
		return err
	}
	if result1.Failure != nil {
		if err := writer.WriteInt32(int32((*result1.Failure).OperationIndex)); err != nil {
			return err
		}
		if err := writer.WriteInt32(int32((*result1.Failure).Kind)); err != nil {
			return err
		}
		if err := writer.WriteInt32(int32((*result1.Failure).ServerCode)); err != nil {
			return err
		}
		if err := writer.WriteBool(bool((*result1.Failure).StateUnknown)); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodeDBServiceExecuteMongoResponse 按固定契约顺序解码并校验完整载荷。
func decodeDBServiceExecuteMongoResponse(data []byte) (result1 MongoResult, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var length1 int
	var isNil2 bool
	length1, isNil2, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length1, 72)
	if decodeErr != nil {
		return
	}
	if !isNil2 {
		result1.Results = make([]MongoOperationResult, length1)
		for index3 := 0; index3 < length1; index3++ {
			var decoded4 int32
			decoded4, decodeErr = reader.ReadInt32()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].Status = MongoOperationStatus(decoded4)
			var length5 int
			var isNil6 bool
			length5, isNil6, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length5, 4)
			if decodeErr != nil {
				return
			}
			if !isNil6 {
				result1.Results[index3].Documents = make([][]byte, length5)
				for index7 := 0; index7 < length5; index7++ {
					var decoded8 []byte
					decoded8, decodeErr = reader.ReadBytes()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Documents[index7] = []byte(decoded8)
				}
			}
			var decoded9 int64
			decoded9, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].Count = int64(decoded9)
			var decoded10 int64
			decoded10, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].InsertedCount = int64(decoded10)
			var decoded11 int64
			decoded11, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].MatchedCount = int64(decoded11)
			var decoded12 int64
			decoded12, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].ModifiedCount = int64(decoded12)
			var decoded13 int64
			decoded13, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].DeletedCount = int64(decoded13)
			var decoded14 int64
			decoded14, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].UpsertedCount = int64(decoded14)
			var length15 int
			var isNil16 bool
			length15, isNil16, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length15, 5)
			if decodeErr != nil {
				return
			}
			if !isNil16 {
				result1.Results[index3].InsertedIDs = make([]MongoBSONValue, length15)
				for index17 := 0; index17 < length15; index17++ {
					var decoded18 byte
					decoded18, decodeErr = reader.ReadUint8()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].InsertedIDs[index17].Type = byte(decoded18)
					var decoded19 []byte
					decoded19, decodeErr = reader.ReadBytes()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].InsertedIDs[index17].Value = []byte(decoded19)
				}
			}
			var length20 int
			var isNil21 bool
			length20, isNil21, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length20, 5)
			if decodeErr != nil {
				return
			}
			if !isNil21 {
				result1.Results[index3].UpsertedIDs = make([]MongoBSONValue, length20)
				for index22 := 0; index22 < length20; index22++ {
					var decoded23 byte
					decoded23, decodeErr = reader.ReadUint8()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].UpsertedIDs[index22].Type = byte(decoded23)
					var decoded24 []byte
					decoded24, decodeErr = reader.ReadBytes()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].UpsertedIDs[index22].Value = []byte(decoded24)
				}
			}
			var length25 int
			var isNil26 bool
			length25, isNil26, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length25, 12)
			if decodeErr != nil {
				return
			}
			if !isNil26 {
				result1.Results[index3].WriteFailures = make([]MongoWriteFailure, length25)
				for index27 := 0; index27 < length25; index27++ {
					var decoded28 int32
					decoded28, decodeErr = reader.ReadInt32()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].WriteFailures[index27].DocumentIndex = int32(decoded28)
					var decoded29 int32
					decoded29, decodeErr = reader.ReadInt32()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].WriteFailures[index27].Kind = MongoFailureKind(decoded29)
					var decoded30 int32
					decoded30, decodeErr = reader.ReadInt32()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].WriteFailures[index27].ServerCode = int32(decoded30)
				}
			}
			var decoded31 []byte
			decoded31, decodeErr = reader.ReadBytes()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].CommandResponse = []byte(decoded31)
		}
	}
	var present32 bool
	present32, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present32 {
		result1.Failure = (*MongoExecutionFailure)(new(MongoExecutionFailure))
		var decoded33 int32
		decoded33, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).OperationIndex = int32(decoded33)
		var decoded34 int32
		decoded34, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).Kind = MongoFailureKind(decoded34)
		var decoded35 int32
		decoded35, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).ServerCode = int32(decoded35)
		var decoded36 bool
		decoded36, decodeErr = reader.ReadBool()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).StateUnknown = bool(decoded36)
	}
	decodeErr = reader.Done()
	return
}

// AwaitExecuteMongo 以顺序编程外观等待 RPC 结果。
func (client DBServiceClient) AwaitExecuteMongo(ctx context.Context, arg1 MongoRequest) (result1 MongoResult, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, dBServiceExecuteMongoMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeDBServiceExecuteMongoRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, dBServiceExecuteMongoMethodID, request, func(data []byte) error {
		result1, err = decodeDBServiceExecuteMongoResponse(data)
		return err
	})
	return
}

// CallExecuteMongo 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client DBServiceClient) CallExecuteMongo(ctx context.Context, arg1 MongoRequest) (result1 MongoResult, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, dBServiceExecuteMongoMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeDBServiceExecuteMongoRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, dBServiceExecuteMongoMethodID, request, func(data []byte) error {
		result1, err = decodeDBServiceExecuteMongoResponse(data)
		return err
	})
	return
}

// AsyncExecuteMongo 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client DBServiceClient) AsyncExecuteMongo(ctx context.Context, arg1 MongoRequest, callback func(context.Context, MongoResult, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, dBServiceExecuteMongoMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeDBServiceExecuteMongoRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, dBServiceExecuteMongoMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(MongoResult), callErr)
			return
		}
		result1, decodeErr := decodeDBServiceExecuteMongoResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyExecuteMongo 提交通知并主动放弃业务结果。
func (client DBServiceClient) NotifyExecuteMongo(ctx context.Context, arg1 MongoRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, dBServiceExecuteMongoMethodID)
	if err != nil {
		return err
	}
	request, err := encodeDBServiceExecuteMongoRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, dBServiceExecuteMongoMethodID, request)
}

// BroadcastExecuteMongo 提交通知并主动放弃业务结果。
func (client DBServiceClient) BroadcastExecuteMongo(ctx context.Context, arg1 MongoRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, dBServiceExecuteMongoMethodID)
	if err != nil {
		return err
	}
	request, err := encodeDBServiceExecuteMongoRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, dBServiceExecuteMongoMethodID, request)
}

// encodeDBServiceExecuteRedisRequest 计算并一次写入当前方法请求载荷。
func encodeDBServiceExecuteRedisRequest(client rpc.Client, kind rpc.CallKind, arg1 RedisRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.DispatchKey)); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.AddContainer(len(arg1.Commands), arg1.Commands == nil); err != nil {
		return nil, err
	}
	for index1 := range arg1.Commands {
		_ = index1
		if err := sizer.AddString(string(arg1.Commands[index1].Name)); err != nil {
			return nil, err
		}
		if err := sizer.AddContainer(len(arg1.Commands[index1].Args), arg1.Commands[index1].Args == nil); err != nil {
			return nil, err
		}
		for index2 := range arg1.Commands[index1].Args {
			_ = index2
			if err := sizer.AddBytes([]byte(arg1.Commands[index1].Args[index2])); err != nil {
				return nil, err
			}
		}
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	if arg1.Script != nil {
		if err := sizer.AddString(string((*arg1.Script).ID)); err != nil {
			return nil, err
		}
		if err := sizer.AddContainer(len((*arg1.Script).Keys), (*arg1.Script).Keys == nil); err != nil {
			return nil, err
		}
		for index3 := range (*arg1.Script).Keys {
			_ = index3
			if err := sizer.AddString(string((*arg1.Script).Keys[index3])); err != nil {
				return nil, err
			}
		}
		if err := sizer.AddContainer(len((*arg1.Script).Args), (*arg1.Script).Args == nil); err != nil {
			return nil, err
		}
		for index4 := range (*arg1.Script).Args {
			_ = index4
			if err := sizer.AddBytes([]byte((*arg1.Script).Args[index4])); err != nil {
				return nil, err
			}
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.DispatchKey)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt32(int32(arg1.ExecuteMode)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteContainer(len(arg1.Commands), arg1.Commands == nil); err != nil {
		buffer.Release()
		return nil, err
	}
	for index5 := range arg1.Commands {
		if err := writer.WriteString(string(arg1.Commands[index5].Name)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WriteContainer(len(arg1.Commands[index5].Args), arg1.Commands[index5].Args == nil); err != nil {
			buffer.Release()
			return nil, err
		}
		for index6 := range arg1.Commands[index5].Args {
			if err := writer.WriteBytes([]byte(arg1.Commands[index5].Args[index6])); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.WritePresence(arg1.Script != nil); err != nil {
		buffer.Release()
		return nil, err
	}
	if arg1.Script != nil {
		if err := writer.WriteString(string((*arg1.Script).ID)); err != nil {
			buffer.Release()
			return nil, err
		}
		if err := writer.WriteContainer(len((*arg1.Script).Keys), (*arg1.Script).Keys == nil); err != nil {
			buffer.Release()
			return nil, err
		}
		for index7 := range (*arg1.Script).Keys {
			if err := writer.WriteString(string((*arg1.Script).Keys[index7])); err != nil {
				buffer.Release()
				return nil, err
			}
		}
		if err := writer.WriteContainer(len((*arg1.Script).Args), (*arg1.Script).Args == nil); err != nil {
			buffer.Release()
			return nil, err
		}
		for index8 := range (*arg1.Script).Args {
			if err := writer.WriteBytes([]byte((*arg1.Script).Args[index8])); err != nil {
				buffer.Release()
				return nil, err
			}
		}
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeDBServiceExecuteRedisRequest 按固定契约顺序解码并校验完整载荷。
func decodeDBServiceExecuteRedisRequest(data []byte) (arg1 RedisRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.DispatchKey = string(decoded1)
	var decoded2 int32
	decoded2, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.ExecuteMode = RedisExecuteMode(decoded2)
	var length3 int
	var isNil4 bool
	length3, isNil4, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length3, 8)
	if decodeErr != nil {
		return
	}
	if !isNil4 {
		arg1.Commands = make([]RedisCommand, length3)
		for index5 := 0; index5 < length3; index5++ {
			var decoded6 string
			decoded6, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			arg1.Commands[index5].Name = string(decoded6)
			var length7 int
			var isNil8 bool
			length7, isNil8, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length7, 4)
			if decodeErr != nil {
				return
			}
			if !isNil8 {
				arg1.Commands[index5].Args = make([][]byte, length7)
				for index9 := 0; index9 < length7; index9++ {
					var decoded10 []byte
					decoded10, decodeErr = reader.ReadBytes()
					if decodeErr != nil {
						return
					}
					arg1.Commands[index5].Args[index9] = []byte(decoded10)
				}
			}
		}
	}
	var present11 bool
	present11, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present11 {
		arg1.Script = (*RedisScriptCall)(new(RedisScriptCall))
		var decoded12 string
		decoded12, decodeErr = reader.ReadString()
		if decodeErr != nil {
			return
		}
		(*arg1.Script).ID = string(decoded12)
		var length13 int
		var isNil14 bool
		length13, isNil14, decodeErr = reader.ReadContainer()
		if decodeErr != nil {
			return
		}
		decodeErr = reader.CheckElements(length13, 4)
		if decodeErr != nil {
			return
		}
		if !isNil14 {
			(*arg1.Script).Keys = make([]string, length13)
			for index15 := 0; index15 < length13; index15++ {
				var decoded16 string
				decoded16, decodeErr = reader.ReadString()
				if decodeErr != nil {
					return
				}
				(*arg1.Script).Keys[index15] = string(decoded16)
			}
		}
		var length17 int
		var isNil18 bool
		length17, isNil18, decodeErr = reader.ReadContainer()
		if decodeErr != nil {
			return
		}
		decodeErr = reader.CheckElements(length17, 4)
		if decodeErr != nil {
			return
		}
		if !isNil18 {
			(*arg1.Script).Args = make([][]byte, length17)
			for index19 := 0; index19 < length17; index19++ {
				var decoded20 []byte
				decoded20, decodeErr = reader.ReadBytes()
				if decodeErr != nil {
					return
				}
				(*arg1.Script).Args[index19] = []byte(decoded20)
			}
		}
	}
	decodeErr = reader.Done()
	return
}

// encodeDBServiceExecuteRedisResponse 计算并一次写入当前方法响应载荷。
func encodeDBServiceExecuteRedisResponse(response *rpc.ResponseWriter, result1 RedisResult) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddContainer(len(result1.Results), result1.Results == nil); err != nil {
		return err
	}
	for index1 := range result1.Results {
		_ = index1
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.AddContainer(len(result1.Results[index1].Value.Nodes), result1.Results[index1].Value.Nodes == nil); err != nil {
			return err
		}
		for index2 := range result1.Results[index1].Value.Nodes {
			_ = index2
			if err := sizer.Add(4); err != nil {
				return err
			}
			if err := sizer.AddBytes([]byte(result1.Results[index1].Value.Nodes[index2].Bytes)); err != nil {
				return err
			}
			if err := sizer.Add(8); err != nil {
				return err
			}
			if err := sizer.Add(8); err != nil {
				return err
			}
			if err := sizer.Add(1); err != nil {
				return err
			}
			if err := sizer.AddContainer(len(result1.Results[index1].Value.Nodes[index2].Children), result1.Results[index1].Value.Nodes[index2].Children == nil); err != nil {
				return err
			}
			for index3 := range result1.Results[index1].Value.Nodes[index2].Children {
				_ = index3
				if err := sizer.Add(4); err != nil {
					return err
				}
			}
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
		if result1.Results[index1].Failure != nil {
			if err := sizer.Add(4); err != nil {
				return err
			}
		}
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if result1.Failure != nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteContainer(len(result1.Results), result1.Results == nil); err != nil {
		return err
	}
	for index4 := range result1.Results {
		if err := writer.WriteInt32(int32(result1.Results[index4].Status)); err != nil {
			return err
		}
		if err := writer.WriteUint32(uint32(result1.Results[index4].Value.RootIndex)); err != nil {
			return err
		}
		if err := writer.WriteContainer(len(result1.Results[index4].Value.Nodes), result1.Results[index4].Value.Nodes == nil); err != nil {
			return err
		}
		for index5 := range result1.Results[index4].Value.Nodes {
			if err := writer.WriteInt32(int32(result1.Results[index4].Value.Nodes[index5].Kind)); err != nil {
				return err
			}
			if err := writer.WriteBytes([]byte(result1.Results[index4].Value.Nodes[index5].Bytes)); err != nil {
				return err
			}
			if err := writer.WriteInt64(int64(result1.Results[index4].Value.Nodes[index5].Integer)); err != nil {
				return err
			}
			if err := writer.WriteFloat64(float64(result1.Results[index4].Value.Nodes[index5].Double)); err != nil {
				return err
			}
			if err := writer.WriteBool(bool(result1.Results[index4].Value.Nodes[index5].Boolean)); err != nil {
				return err
			}
			if err := writer.WriteContainer(len(result1.Results[index4].Value.Nodes[index5].Children), result1.Results[index4].Value.Nodes[index5].Children == nil); err != nil {
				return err
			}
			for index6 := range result1.Results[index4].Value.Nodes[index5].Children {
				if err := writer.WriteUint32(uint32(result1.Results[index4].Value.Nodes[index5].Children[index6])); err != nil {
					return err
				}
			}
		}
		if err := writer.WritePresence(result1.Results[index4].Failure != nil); err != nil {
			return err
		}
		if result1.Results[index4].Failure != nil {
			if err := writer.WriteInt32(int32((*result1.Results[index4].Failure).Kind)); err != nil {
				return err
			}
		}
	}
	if err := writer.WritePresence(result1.Failure != nil); err != nil {
		return err
	}
	if result1.Failure != nil {
		if err := writer.WriteInt32(int32((*result1.Failure).Kind)); err != nil {
			return err
		}
		if err := writer.WriteBool(bool((*result1.Failure).StateUnknown)); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodeDBServiceExecuteRedisResponse 按固定契约顺序解码并校验完整载荷。
func decodeDBServiceExecuteRedisResponse(data []byte) (result1 RedisResult, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var length1 int
	var isNil2 bool
	length1, isNil2, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length1, 13)
	if decodeErr != nil {
		return
	}
	if !isNil2 {
		result1.Results = make([]RedisCommandResult, length1)
		for index3 := 0; index3 < length1; index3++ {
			var decoded4 int32
			decoded4, decodeErr = reader.ReadInt32()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].Status = RedisCommandStatus(decoded4)
			var decoded5 uint32
			decoded5, decodeErr = reader.ReadUint32()
			if decodeErr != nil {
				return
			}
			result1.Results[index3].Value.RootIndex = uint32(decoded5)
			var length6 int
			var isNil7 bool
			length6, isNil7, decodeErr = reader.ReadContainer()
			if decodeErr != nil {
				return
			}
			decodeErr = reader.CheckElements(length6, 29)
			if decodeErr != nil {
				return
			}
			if !isNil7 {
				result1.Results[index3].Value.Nodes = make([]RedisValueNode, length6)
				for index8 := 0; index8 < length6; index8++ {
					var decoded9 int32
					decoded9, decodeErr = reader.ReadInt32()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Value.Nodes[index8].Kind = RedisValueKind(decoded9)
					var decoded10 []byte
					decoded10, decodeErr = reader.ReadBytes()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Value.Nodes[index8].Bytes = []byte(decoded10)
					var decoded11 int64
					decoded11, decodeErr = reader.ReadInt64()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Value.Nodes[index8].Integer = int64(decoded11)
					var decoded12 float64
					decoded12, decodeErr = reader.ReadFloat64()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Value.Nodes[index8].Double = float64(decoded12)
					var decoded13 bool
					decoded13, decodeErr = reader.ReadBool()
					if decodeErr != nil {
						return
					}
					result1.Results[index3].Value.Nodes[index8].Boolean = bool(decoded13)
					var length14 int
					var isNil15 bool
					length14, isNil15, decodeErr = reader.ReadContainer()
					if decodeErr != nil {
						return
					}
					decodeErr = reader.CheckElements(length14, 4)
					if decodeErr != nil {
						return
					}
					if !isNil15 {
						result1.Results[index3].Value.Nodes[index8].Children = make([]uint32, length14)
						for index16 := 0; index16 < length14; index16++ {
							var decoded17 uint32
							decoded17, decodeErr = reader.ReadUint32()
							if decodeErr != nil {
								return
							}
							result1.Results[index3].Value.Nodes[index8].Children[index16] = uint32(decoded17)
						}
					}
				}
			}
			var present18 bool
			present18, decodeErr = reader.ReadPresence()
			if decodeErr != nil {
				return
			}
			if present18 {
				result1.Results[index3].Failure = (*RedisCommandFailure)(new(RedisCommandFailure))
				var decoded19 int32
				decoded19, decodeErr = reader.ReadInt32()
				if decodeErr != nil {
					return
				}
				(*result1.Results[index3].Failure).Kind = RedisFailureKind(decoded19)
			}
		}
	}
	var present20 bool
	present20, decodeErr = reader.ReadPresence()
	if decodeErr != nil {
		return
	}
	if present20 {
		result1.Failure = (*RedisExecutionFailure)(new(RedisExecutionFailure))
		var decoded21 int32
		decoded21, decodeErr = reader.ReadInt32()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).Kind = RedisFailureKind(decoded21)
		var decoded22 bool
		decoded22, decodeErr = reader.ReadBool()
		if decodeErr != nil {
			return
		}
		(*result1.Failure).StateUnknown = bool(decoded22)
	}
	decodeErr = reader.Done()
	return
}

// AwaitExecuteRedis 以顺序编程外观等待 RPC 结果。
func (client DBServiceClient) AwaitExecuteRedis(ctx context.Context, arg1 RedisRequest) (result1 RedisResult, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, dBServiceExecuteRedisMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeDBServiceExecuteRedisRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, dBServiceExecuteRedisMethodID, request, func(data []byte) error {
		result1, err = decodeDBServiceExecuteRedisResponse(data)
		return err
	})
	return
}

// CallExecuteRedis 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client DBServiceClient) CallExecuteRedis(ctx context.Context, arg1 RedisRequest) (result1 RedisResult, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, dBServiceExecuteRedisMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeDBServiceExecuteRedisRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, dBServiceExecuteRedisMethodID, request, func(data []byte) error {
		result1, err = decodeDBServiceExecuteRedisResponse(data)
		return err
	})
	return
}

// AsyncExecuteRedis 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client DBServiceClient) AsyncExecuteRedis(ctx context.Context, arg1 RedisRequest, callback func(context.Context, RedisResult, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, dBServiceExecuteRedisMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeDBServiceExecuteRedisRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, dBServiceExecuteRedisMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(RedisResult), callErr)
			return
		}
		result1, decodeErr := decodeDBServiceExecuteRedisResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyExecuteRedis 提交通知并主动放弃业务结果。
func (client DBServiceClient) NotifyExecuteRedis(ctx context.Context, arg1 RedisRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, dBServiceExecuteRedisMethodID)
	if err != nil {
		return err
	}
	request, err := encodeDBServiceExecuteRedisRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, dBServiceExecuteRedisMethodID, request)
}

// BroadcastExecuteRedis 提交通知并主动放弃业务结果。
func (client DBServiceClient) BroadcastExecuteRedis(ctx context.Context, arg1 RedisRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, dBServiceExecuteRedisMethodID)
	if err != nil {
		return err
	}
	request, err := encodeDBServiceExecuteRedisRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, dBServiceExecuteRedisMethodID, request)
}

// dBServiceDispatcher 把 MethodID 静态分派到 DBService 实现。
type dBServiceDispatcher struct{ impl DBService }

// NewDBServiceDispatcher 创建不使用反射的静态 Dispatcher。
func NewDBServiceDispatcher(impl DBService) rpc.Dispatcher {
	return &dBServiceDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *dBServiceDispatcher) ContractID() rpc.ContractID { return dBServiceContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *dBServiceDispatcher) Fingerprint() rpc.ContractFingerprint {
	return dBServiceFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *dBServiceDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case dBServiceExecuteMongoMethodID:
		arg1, err := decodeDBServiceExecuteMongoRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.ExecuteMongo(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.ExecuteMongo(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeDBServiceExecuteMongoResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case dBServiceExecuteRedisMethodID:
		arg1, err := decodeDBServiceExecuteRedisRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.ExecuteRedis(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.ExecuteRedis(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeDBServiceExecuteRedisResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

func init() {
	rpc.RegisterGeneratedContract(rpc.GeneratedContractDescriptor{
		ServiceName:  "DBService",
		ContractName: "origingame/protocol/rpc.DBService",
		ContractID:   dBServiceContractID,
		Fingerprint:  dBServiceFingerprint,
		NewDispatcher: func(implementation any) (rpc.Dispatcher, bool) {
			target, ok := implementation.(DBService)
			if !ok {
				return nil, false
			}
			return NewDBServiceDispatcher(target), true
		},
	})
}
