// Code generated by origingen rpc; DO NOT EDIT.

package rpcapi

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
	commonpb "origingame/protocol/common"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const gameServiceContractID rpc.ContractID = 0x95218c789ce42604

var gameServiceFingerprint = rpc.ContractFingerprint{0x61, 0xa9, 0x27, 0x0d, 0x8f, 0xd5, 0x4e, 0x3b, 0x77, 0x96, 0xf4, 0x61, 0x1f, 0x6a, 0xba, 0x70, 0x54, 0x9f, 0x2b, 0x68, 0xb8, 0xe8, 0x4b, 0xe7, 0xf6, 0xea, 0x3b, 0x9d, 0x1f, 0x62, 0xfd, 0x5b}

const gameServiceHandlePlayerMessageMethodID rpc.MethodID = 0x60277046a6f1f11e
const gameServiceLoginPlayerMethodID rpc.MethodID = 0x0d079b9a2e5bf1d1
const gameServicePlayerDisconnectedMethodID rpc.MethodID = 0xe316d334190c2725

// GameServiceClient 是 origingame/protocol/rpc.GameService 的强类型生成客户端。
type GameServiceClient struct {
	client rpc.Client
}

// NewGameServiceClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewGameServiceClient(owner service.IService, target rpc.Target) GameServiceClient {
	return GameServiceClient{client: rpc.NewGeneratedClient(owner, target, gameServiceContractID, gameServiceFingerprint)}
}

// BindGameService 使用契约默认 ServiceName "GameService" 绑定轻量客户端。
func BindGameService(owner service.IService) GameServiceClient {
	return NewGameServiceClient(owner, rpc.ToService("GameService"))
}

// BindGameServiceTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindGameServiceTo(owner service.IService, serviceName string) GameServiceClient {
	return NewGameServiceClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client GameServiceClient) OnNode(nodeID string) GameServiceClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// WhereLabels 派生按 Node Labels 精确筛选候选的客户端。
func (client GameServiceClient) WhereLabels(labels map[string]string) GameServiceClient {
	client.client = client.client.WhereLabels(labels)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client GameServiceClient) RouteRoundRobin() GameServiceClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client GameServiceClient) RouteRandom() GameServiceClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client GameServiceClient) Route(key any) GameServiceClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client GameServiceClient) RouteBy(selector rpc.RouteSelector) GameServiceClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client GameServiceClient) IncludeRetired() GameServiceClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodeGameServiceHandlePlayerMessageRequest 计算并一次写入当前方法请求载荷。
func encodeGameServiceHandlePlayerMessageRequest(client rpc.Client, kind rpc.CallKind, arg1 PlayerMessageRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.GatewayConnectionID)); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.AddBytes([]byte(arg1.Body)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.GatewayConnectionID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt32(int32(arg1.MessageID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteUint32(uint32(arg1.Sequence)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteBytes([]byte(arg1.Body)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeGameServiceHandlePlayerMessageRequest 按固定契约顺序解码并校验完整载荷。
func decodeGameServiceHandlePlayerMessageRequest(data []byte) (arg1 PlayerMessageRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayConnectionID = string(decoded1)
	var decoded2 int32
	decoded2, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.MessageID = commonpb.MessageID(decoded2)
	var decoded3 uint32
	decoded3, decodeErr = reader.ReadUint32()
	if decodeErr != nil {
		return
	}
	arg1.Sequence = uint32(decoded3)
	var decoded4 []byte
	decoded4, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg1.Body = []byte(decoded4)
	decodeErr = reader.Done()
	return
}

// encodeGameServiceHandlePlayerMessageResponse 计算并一次写入当前方法响应载荷。
func encodeGameServiceHandlePlayerMessageResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodeGameServiceHandlePlayerMessageResponse 按固定契约顺序解码并校验完整载荷。
func decodeGameServiceHandlePlayerMessageResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitHandlePlayerMessage 以顺序编程外观等待 RPC 结果。
func (client GameServiceClient) AwaitHandlePlayerMessage(ctx context.Context, arg1 PlayerMessageRequest) (err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, gameServiceHandlePlayerMessageMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServiceHandlePlayerMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, gameServiceHandlePlayerMessageMethodID, request, func(data []byte) error {
		return decodeGameServiceHandlePlayerMessageResponse(data)
	})
	return
}

// CallHandlePlayerMessage 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client GameServiceClient) CallHandlePlayerMessage(ctx context.Context, arg1 PlayerMessageRequest) (err error) {
	preparedClient, err := client.client.PrepareCall(ctx, gameServiceHandlePlayerMessageMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServiceHandlePlayerMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, gameServiceHandlePlayerMessageMethodID, request, func(data []byte) error {
		return decodeGameServiceHandlePlayerMessageResponse(data)
	})
	return
}

// AsyncHandlePlayerMessage 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client GameServiceClient) AsyncHandlePlayerMessage(ctx context.Context, arg1 PlayerMessageRequest, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, gameServiceHandlePlayerMessageMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeGameServiceHandlePlayerMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, gameServiceHandlePlayerMessageMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodeGameServiceHandlePlayerMessageResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifyHandlePlayerMessage 提交通知并主动放弃业务结果。
func (client GameServiceClient) NotifyHandlePlayerMessage(ctx context.Context, arg1 PlayerMessageRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, gameServiceHandlePlayerMessageMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServiceHandlePlayerMessageRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, gameServiceHandlePlayerMessageMethodID, request)
}

// BroadcastHandlePlayerMessage 提交通知并主动放弃业务结果。
func (client GameServiceClient) BroadcastHandlePlayerMessage(ctx context.Context, arg1 PlayerMessageRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, gameServiceHandlePlayerMessageMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServiceHandlePlayerMessageRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, gameServiceHandlePlayerMessageMethodID, request)
}

// encodeGameServiceLoginPlayerRequest 计算并一次写入当前方法请求载荷。
func encodeGameServiceLoginPlayerRequest(client rpc.Client, kind rpc.CallKind, arg1 LoginPlayerRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.AccountID)); err != nil {
		return nil, err
	}
	if err := sizer.Add(8); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg1.GatewayNodeID)); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg1.GatewayConnectionID)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.AccountID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt64(int64(arg1.ShowAreaID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg1.GatewayNodeID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg1.GatewayConnectionID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeGameServiceLoginPlayerRequest 按固定契约顺序解码并校验完整载荷。
func decodeGameServiceLoginPlayerRequest(data []byte) (arg1 LoginPlayerRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.AccountID = string(decoded1)
	var decoded2 int64
	decoded2, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	arg1.ShowAreaID = int64(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayNodeID = string(decoded3)
	var decoded4 string
	decoded4, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayConnectionID = string(decoded4)
	decodeErr = reader.Done()
	return
}

// encodeGameServiceLoginPlayerResponse 计算并一次写入当前方法响应载荷。
func encodeGameServiceLoginPlayerResponse(response *rpc.ResponseWriter, result1 *commonpb.LoginPlayerResult) error {
	sizer := rpc.NewSizer()
	if result1 == nil {
		if err := sizer.Add(4); err != nil {
			return err
		}
	} else {
		if err := sizer.AddProto(result1); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if result1 == nil {
		if err := writer.WriteNil(); err != nil {
			return err
		}
	} else {
		if err := writer.WriteProto(result1); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodeGameServiceLoginPlayerResponse 按固定契约顺序解码并校验完整载荷。
func decodeGameServiceLoginPlayerResponse(data []byte) (result1 *commonpb.LoginPlayerResult, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var payload1 []byte
	var isNil2 bool
	payload1, isNil2, decodeErr = reader.ReadProtoPayload()
	if decodeErr != nil {
		return
	}
	if !isNil2 {
		result1 = new(commonpb.LoginPlayerResult)
		decodeErr = rpc.UnmarshalProto(payload1, result1, true)
		if decodeErr != nil {
			return
		}
	}
	decodeErr = reader.Done()
	return
}

// AwaitLoginPlayer 以顺序编程外观等待 RPC 结果。
func (client GameServiceClient) AwaitLoginPlayer(ctx context.Context, arg1 LoginPlayerRequest) (result1 *commonpb.LoginPlayerResult, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, gameServiceLoginPlayerMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServiceLoginPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, gameServiceLoginPlayerMethodID, request, func(data []byte) error {
		result1, err = decodeGameServiceLoginPlayerResponse(data)
		return err
	})
	return
}

// CallLoginPlayer 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client GameServiceClient) CallLoginPlayer(ctx context.Context, arg1 LoginPlayerRequest) (result1 *commonpb.LoginPlayerResult, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, gameServiceLoginPlayerMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServiceLoginPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, gameServiceLoginPlayerMethodID, request, func(data []byte) error {
		result1, err = decodeGameServiceLoginPlayerResponse(data)
		return err
	})
	return
}

// AsyncLoginPlayer 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client GameServiceClient) AsyncLoginPlayer(ctx context.Context, arg1 LoginPlayerRequest, callback func(context.Context, *commonpb.LoginPlayerResult, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, gameServiceLoginPlayerMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeGameServiceLoginPlayerRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, gameServiceLoginPlayerMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(*commonpb.LoginPlayerResult), callErr)
			return
		}
		result1, decodeErr := decodeGameServiceLoginPlayerResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyLoginPlayer 提交通知并主动放弃业务结果。
func (client GameServiceClient) NotifyLoginPlayer(ctx context.Context, arg1 LoginPlayerRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, gameServiceLoginPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServiceLoginPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, gameServiceLoginPlayerMethodID, request)
}

// BroadcastLoginPlayer 提交通知并主动放弃业务结果。
func (client GameServiceClient) BroadcastLoginPlayer(ctx context.Context, arg1 LoginPlayerRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, gameServiceLoginPlayerMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServiceLoginPlayerRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, gameServiceLoginPlayerMethodID, request)
}

// encodeGameServicePlayerDisconnectedRequest 计算并一次写入当前方法请求载荷。
func encodeGameServicePlayerDisconnectedRequest(client rpc.Client, kind rpc.CallKind, arg1 PlayerDisconnectedRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.GatewayConnectionID)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.GatewayConnectionID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeGameServicePlayerDisconnectedRequest 按固定契约顺序解码并校验完整载荷。
func decodeGameServicePlayerDisconnectedRequest(data []byte) (arg1 PlayerDisconnectedRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayConnectionID = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodeGameServicePlayerDisconnectedResponse 计算并一次写入当前方法响应载荷。
func encodeGameServicePlayerDisconnectedResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodeGameServicePlayerDisconnectedResponse 按固定契约顺序解码并校验完整载荷。
func decodeGameServicePlayerDisconnectedResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitPlayerDisconnected 以顺序编程外观等待 RPC 结果。
func (client GameServiceClient) AwaitPlayerDisconnected(ctx context.Context, arg1 PlayerDisconnectedRequest) (err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, gameServicePlayerDisconnectedMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServicePlayerDisconnectedRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, gameServicePlayerDisconnectedMethodID, request, func(data []byte) error {
		return decodeGameServicePlayerDisconnectedResponse(data)
	})
	return
}

// CallPlayerDisconnected 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client GameServiceClient) CallPlayerDisconnected(ctx context.Context, arg1 PlayerDisconnectedRequest) (err error) {
	preparedClient, err := client.client.PrepareCall(ctx, gameServicePlayerDisconnectedMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGameServicePlayerDisconnectedRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, gameServicePlayerDisconnectedMethodID, request, func(data []byte) error {
		return decodeGameServicePlayerDisconnectedResponse(data)
	})
	return
}

// AsyncPlayerDisconnected 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client GameServiceClient) AsyncPlayerDisconnected(ctx context.Context, arg1 PlayerDisconnectedRequest, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, gameServicePlayerDisconnectedMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeGameServicePlayerDisconnectedRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, gameServicePlayerDisconnectedMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodeGameServicePlayerDisconnectedResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifyPlayerDisconnected 提交通知并主动放弃业务结果。
func (client GameServiceClient) NotifyPlayerDisconnected(ctx context.Context, arg1 PlayerDisconnectedRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, gameServicePlayerDisconnectedMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServicePlayerDisconnectedRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, gameServicePlayerDisconnectedMethodID, request)
}

// BroadcastPlayerDisconnected 提交通知并主动放弃业务结果。
func (client GameServiceClient) BroadcastPlayerDisconnected(ctx context.Context, arg1 PlayerDisconnectedRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, gameServicePlayerDisconnectedMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGameServicePlayerDisconnectedRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, gameServicePlayerDisconnectedMethodID, request)
}

// gameServiceDispatcher 把 MethodID 静态分派到 GameService 实现。
type gameServiceDispatcher struct{ impl GameService }

// NewGameServiceDispatcher 创建不使用反射的静态 Dispatcher。
func NewGameServiceDispatcher(impl GameService) rpc.Dispatcher {
	return &gameServiceDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *gameServiceDispatcher) ContractID() rpc.ContractID { return gameServiceContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *gameServiceDispatcher) Fingerprint() rpc.ContractFingerprint {
	return gameServiceFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *gameServiceDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case gameServiceHandlePlayerMessageMethodID:
		arg1, err := decodeGameServiceHandlePlayerMessageRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.HandlePlayerMessage(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.HandlePlayerMessage(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeGameServiceHandlePlayerMessageResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	case gameServiceLoginPlayerMethodID:
		arg1, err := decodeGameServiceLoginPlayerRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.LoginPlayer(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.LoginPlayer(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeGameServiceLoginPlayerResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case gameServicePlayerDisconnectedMethodID:
		arg1, err := decodeGameServicePlayerDisconnectedRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.PlayerDisconnected(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.PlayerDisconnected(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeGameServicePlayerDisconnectedResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

func init() {
	rpc.RegisterGeneratedContract(rpc.GeneratedContractDescriptor{
		ServiceName:  "GameService",
		ContractName: "origingame/protocol/rpc.GameService",
		ContractID:   gameServiceContractID,
		Fingerprint:  gameServiceFingerprint,
		NewDispatcher: func(implementation any) (rpc.Dispatcher, bool) {
			target, ok := implementation.(GameService)
			if !ok {
				return nil, false
			}
			return NewGameServiceDispatcher(target), true
		},
	})
}
