// Code generated by origingen rpc; DO NOT EDIT.

package rpcapi

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
	commonpb "origingame/protocol/common"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const gatewayServiceContractID rpc.ContractID = 0xc2a033a015d7fa52

var gatewayServiceFingerprint = rpc.ContractFingerprint{0x74, 0x1a, 0x5c, 0x6f, 0xfc, 0x00, 0xa2, 0x44, 0xae, 0x09, 0xe7, 0x89, 0xcd, 0xce, 0xf2, 0xeb, 0xfa, 0x1d, 0x72, 0x72, 0xce, 0xe2, 0xad, 0xce, 0x69, 0x7e, 0x51, 0x53, 0x5e, 0xf4, 0x29, 0xa7}

const gatewayServiceCloseClientConnectionMethodID rpc.MethodID = 0xbae5f82f14fb7749
const gatewayServiceSendClientMessageMethodID rpc.MethodID = 0xf8b566e2d695ade3

// GatewayServiceClient 是 origingame/protocol/rpc.GatewayService 的强类型生成客户端。
type GatewayServiceClient struct {
	client rpc.Client
}

// NewGatewayServiceClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewGatewayServiceClient(owner service.IService, target rpc.Target) GatewayServiceClient {
	return GatewayServiceClient{client: rpc.NewGeneratedClient(owner, target, gatewayServiceContractID, gatewayServiceFingerprint)}
}

// BindGatewayService 使用契约默认 ServiceName "GatewayService" 绑定轻量客户端。
func BindGatewayService(owner service.IService) GatewayServiceClient {
	return NewGatewayServiceClient(owner, rpc.ToService("GatewayService"))
}

// BindGatewayServiceTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindGatewayServiceTo(owner service.IService, serviceName string) GatewayServiceClient {
	return NewGatewayServiceClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client GatewayServiceClient) OnNode(nodeID string) GatewayServiceClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// WhereLabels 派生按 Node Labels 精确筛选候选的客户端。
func (client GatewayServiceClient) WhereLabels(labels map[string]string) GatewayServiceClient {
	client.client = client.client.WhereLabels(labels)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client GatewayServiceClient) RouteRoundRobin() GatewayServiceClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client GatewayServiceClient) RouteRandom() GatewayServiceClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client GatewayServiceClient) Route(key any) GatewayServiceClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client GatewayServiceClient) RouteBy(selector rpc.RouteSelector) GatewayServiceClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client GatewayServiceClient) IncludeRetired() GatewayServiceClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodeGatewayServiceCloseClientConnectionRequest 计算并一次写入当前方法请求载荷。
func encodeGatewayServiceCloseClientConnectionRequest(client rpc.Client, kind rpc.CallKind, arg1 CloseClientConnectionRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.GatewayConnectionID)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.GatewayConnectionID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeGatewayServiceCloseClientConnectionRequest 按固定契约顺序解码并校验完整载荷。
func decodeGatewayServiceCloseClientConnectionRequest(data []byte) (arg1 CloseClientConnectionRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayConnectionID = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodeGatewayServiceCloseClientConnectionResponse 计算并一次写入当前方法响应载荷。
func encodeGatewayServiceCloseClientConnectionResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodeGatewayServiceCloseClientConnectionResponse 按固定契约顺序解码并校验完整载荷。
func decodeGatewayServiceCloseClientConnectionResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitCloseClientConnection 以顺序编程外观等待 RPC 结果。
func (client GatewayServiceClient) AwaitCloseClientConnection(ctx context.Context, arg1 CloseClientConnectionRequest) (err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, gatewayServiceCloseClientConnectionMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGatewayServiceCloseClientConnectionRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, gatewayServiceCloseClientConnectionMethodID, request, func(data []byte) error {
		return decodeGatewayServiceCloseClientConnectionResponse(data)
	})
	return
}

// CallCloseClientConnection 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client GatewayServiceClient) CallCloseClientConnection(ctx context.Context, arg1 CloseClientConnectionRequest) (err error) {
	preparedClient, err := client.client.PrepareCall(ctx, gatewayServiceCloseClientConnectionMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGatewayServiceCloseClientConnectionRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, gatewayServiceCloseClientConnectionMethodID, request, func(data []byte) error {
		return decodeGatewayServiceCloseClientConnectionResponse(data)
	})
	return
}

// AsyncCloseClientConnection 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client GatewayServiceClient) AsyncCloseClientConnection(ctx context.Context, arg1 CloseClientConnectionRequest, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, gatewayServiceCloseClientConnectionMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeGatewayServiceCloseClientConnectionRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, gatewayServiceCloseClientConnectionMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodeGatewayServiceCloseClientConnectionResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifyCloseClientConnection 提交通知并主动放弃业务结果。
func (client GatewayServiceClient) NotifyCloseClientConnection(ctx context.Context, arg1 CloseClientConnectionRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, gatewayServiceCloseClientConnectionMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGatewayServiceCloseClientConnectionRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, gatewayServiceCloseClientConnectionMethodID, request)
}

// BroadcastCloseClientConnection 提交通知并主动放弃业务结果。
func (client GatewayServiceClient) BroadcastCloseClientConnection(ctx context.Context, arg1 CloseClientConnectionRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, gatewayServiceCloseClientConnectionMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGatewayServiceCloseClientConnectionRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, gatewayServiceCloseClientConnectionMethodID, request)
}

// encodeGatewayServiceSendClientMessageRequest 计算并一次写入当前方法请求载荷。
func encodeGatewayServiceSendClientMessageRequest(client rpc.Client, kind rpc.CallKind, arg1 SendClientMessageRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.GatewayConnectionID)); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	if err := sizer.AddBytes([]byte(arg1.Message.Body)); err != nil {
		return nil, err
	}
	if err := sizer.Add(1); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.GatewayConnectionID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt32(int32(arg1.Message.MessageID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteUint32(uint32(arg1.Message.Sequence)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteInt32(int32(arg1.Message.ErrorCode)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteBytes([]byte(arg1.Message.Body)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteBool(bool(arg1.Message.CloseAfterWrite)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeGatewayServiceSendClientMessageRequest 按固定契约顺序解码并校验完整载荷。
func decodeGatewayServiceSendClientMessageRequest(data []byte) (arg1 SendClientMessageRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.GatewayConnectionID = string(decoded1)
	var decoded2 int32
	decoded2, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.Message.MessageID = commonpb.MessageID(decoded2)
	var decoded3 uint32
	decoded3, decodeErr = reader.ReadUint32()
	if decodeErr != nil {
		return
	}
	arg1.Message.Sequence = uint32(decoded3)
	var decoded4 int32
	decoded4, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.Message.ErrorCode = commonpb.ErrorCode(decoded4)
	var decoded5 []byte
	decoded5, decodeErr = reader.ReadBytes()
	if decodeErr != nil {
		return
	}
	arg1.Message.Body = []byte(decoded5)
	var decoded6 bool
	decoded6, decodeErr = reader.ReadBool()
	if decodeErr != nil {
		return
	}
	arg1.Message.CloseAfterWrite = bool(decoded6)
	decodeErr = reader.Done()
	return
}

// encodeGatewayServiceSendClientMessageResponse 计算并一次写入当前方法响应载荷。
func encodeGatewayServiceSendClientMessageResponse(response *rpc.ResponseWriter) error {
	sizer := rpc.NewSizer()
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	return writer.Done()
}

// decodeGatewayServiceSendClientMessageResponse 按固定契约顺序解码并校验完整载荷。
func decodeGatewayServiceSendClientMessageResponse(data []byte) (decodeErr error) {
	reader := rpc.NewResponseReader(data)
	decodeErr = reader.Done()
	return
}

// AwaitSendClientMessage 以顺序编程外观等待 RPC 结果。
func (client GatewayServiceClient) AwaitSendClientMessage(ctx context.Context, arg1 SendClientMessageRequest) (err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, gatewayServiceSendClientMessageMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGatewayServiceSendClientMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, gatewayServiceSendClientMessageMethodID, request, func(data []byte) error {
		return decodeGatewayServiceSendClientMessageResponse(data)
	})
	return
}

// CallSendClientMessage 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client GatewayServiceClient) CallSendClientMessage(ctx context.Context, arg1 SendClientMessageRequest) (err error) {
	preparedClient, err := client.client.PrepareCall(ctx, gatewayServiceSendClientMessageMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeGatewayServiceSendClientMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, gatewayServiceSendClientMessageMethodID, request, func(data []byte) error {
		return decodeGatewayServiceSendClientMessageResponse(data)
	})
	return
}

// AsyncSendClientMessage 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client GatewayServiceClient) AsyncSendClientMessage(ctx context.Context, arg1 SendClientMessageRequest, callback func(context.Context, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, gatewayServiceSendClientMessageMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeGatewayServiceSendClientMessageRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, gatewayServiceSendClientMessageMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, callErr)
			return
		}
		decodeErr := decodeGatewayServiceSendClientMessageResponse(data)
		callback(callbackCtx, decodeErr)
	})
}

// NotifySendClientMessage 提交通知并主动放弃业务结果。
func (client GatewayServiceClient) NotifySendClientMessage(ctx context.Context, arg1 SendClientMessageRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, gatewayServiceSendClientMessageMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGatewayServiceSendClientMessageRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, gatewayServiceSendClientMessageMethodID, request)
}

// BroadcastSendClientMessage 提交通知并主动放弃业务结果。
func (client GatewayServiceClient) BroadcastSendClientMessage(ctx context.Context, arg1 SendClientMessageRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, gatewayServiceSendClientMessageMethodID)
	if err != nil {
		return err
	}
	request, err := encodeGatewayServiceSendClientMessageRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, gatewayServiceSendClientMessageMethodID, request)
}

// gatewayServiceDispatcher 把 MethodID 静态分派到 GatewayService 实现。
type gatewayServiceDispatcher struct{ impl GatewayService }

// NewGatewayServiceDispatcher 创建不使用反射的静态 Dispatcher。
func NewGatewayServiceDispatcher(impl GatewayService) rpc.Dispatcher {
	return &gatewayServiceDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *gatewayServiceDispatcher) ContractID() rpc.ContractID {
	return gatewayServiceContractID
}

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *gatewayServiceDispatcher) Fingerprint() rpc.ContractFingerprint {
	return gatewayServiceFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *gatewayServiceDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case gatewayServiceCloseClientConnectionMethodID:
		arg1, err := decodeGatewayServiceCloseClientConnectionRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.CloseClientConnection(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.CloseClientConnection(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeGatewayServiceCloseClientConnectionResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	case gatewayServiceSendClientMessageMethodID:
		arg1, err := decodeGatewayServiceSendClientMessageRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			callErr := dispatcher.impl.SendClientMessage(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		callErr := dispatcher.impl.SendClientMessage(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeGatewayServiceSendClientMessageResponse(&response); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

func init() {
	rpc.RegisterGeneratedContract(rpc.GeneratedContractDescriptor{
		ServiceName:  "GatewayService",
		ContractName: "origingame/protocol/rpc.GatewayService",
		ContractID:   gatewayServiceContractID,
		Fingerprint:  gatewayServiceFingerprint,
		NewDispatcher: func(implementation any) (rpc.Dispatcher, bool) {
			target, ok := implementation.(GatewayService)
			if !ok {
				return nil, false
			}
			return NewGatewayServiceDispatcher(target), true
		},
	})
}
