// Code generated by origingen rpc; DO NOT EDIT.

package rpcapi

import (
	context "context"
	errs "github.com/duanhf2012/origin/v3/errs"
	rpc "github.com/duanhf2012/origin/v3/rpc"
	service "github.com/duanhf2012/origin/v3/service"
)

const (
	_ uint = rpc.GeneratedABIVersion - 3
	_ uint = 3 - rpc.GeneratedABIVersion
)

const robotServiceContractID rpc.ContractID = 0xbc34a1e3da51d4c5

var robotServiceFingerprint = rpc.ContractFingerprint{0xef, 0xd8, 0xbd, 0x75, 0xba, 0xb0, 0x94, 0x1a, 0x99, 0x83, 0xd1, 0xb0, 0xba, 0xd9, 0xdf, 0x1a, 0xd5, 0xcf, 0x3d, 0xe9, 0x0b, 0x26, 0x5f, 0x22, 0x8e, 0xea, 0x13, 0x12, 0xf9, 0x66, 0xc5, 0x66}

const robotServiceGetRunMethodID rpc.MethodID = 0xdde7dfcc687e53b9
const robotServiceListScenariosMethodID rpc.MethodID = 0xc594d127a09b5a2d
const robotServiceStartRunMethodID rpc.MethodID = 0xaecd6a1ec21303f8
const robotServiceStopRunMethodID rpc.MethodID = 0x232d3a6250c1e2af

// RobotServiceClient 是 origingame/protocol/rpc.RobotService 的强类型生成客户端。
type RobotServiceClient struct {
	client rpc.Client
}

// NewRobotServiceClient 创建绑定 owner 和逻辑目标的轻量客户端。
func NewRobotServiceClient(owner service.IService, target rpc.Target) RobotServiceClient {
	return RobotServiceClient{client: rpc.NewGeneratedClient(owner, target, robotServiceContractID, robotServiceFingerprint)}
}

// BindRobotService 使用契约默认 ServiceName "RobotService" 绑定轻量客户端。
func BindRobotService(owner service.IService) RobotServiceClient {
	return NewRobotServiceClient(owner, rpc.ToService("RobotService"))
}

// BindRobotServiceTo 使用实际 ServiceName 绑定模板改名后的轻量客户端。
func BindRobotServiceTo(owner service.IService, serviceName string) RobotServiceClient {
	return NewRobotServiceClient(owner, rpc.ToService(serviceName))
}

// OnNode 保留已绑定 ServiceName 并把目标收窄到指定 Node。
func (client RobotServiceClient) OnNode(nodeID string) RobotServiceClient {
	client.client = client.client.OnNode(nodeID)
	return client
}

// WhereLabels 派生按 Node Labels 精确筛选候选的客户端。
func (client RobotServiceClient) WhereLabels(labels map[string]string) RobotServiceClient {
	client.client = client.client.WhereLabels(labels)
	return client
}

// RouteRoundRobin 派生显式轮询路由客户端。
func (client RobotServiceClient) RouteRoundRobin() RobotServiceClient {
	client.client = client.client.RouteRoundRobin()
	return client
}

// RouteRandom 派生随机路由客户端。
func (client RobotServiceClient) RouteRandom() RobotServiceClient {
	client.client = client.client.RouteRandom()
	return client
}

// Route 派生稳定业务 Key 路由客户端。
func (client RobotServiceClient) Route(key any) RobotServiceClient {
	client.client = client.client.Route(key)
	return client
}

// RouteBy 派生自定义 Selector 路由客户端。
func (client RobotServiceClient) RouteBy(selector rpc.RouteSelector) RobotServiceClient {
	client.client = client.client.RouteBy(selector)
	return client
}

// IncludeRetired 派生在自动范围中同时接受 Running 和 Retired 的客户端。
func (client RobotServiceClient) IncludeRetired() RobotServiceClient {
	client.client = client.client.IncludeRetired()
	return client
}

// encodeRobotServiceGetRunRequest 计算并一次写入当前方法请求载荷。
func encodeRobotServiceGetRunRequest(client rpc.Client, kind rpc.CallKind, arg1 GetRobotRunRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.RunID)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.RunID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeRobotServiceGetRunRequest 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceGetRunRequest(data []byte) (arg1 GetRobotRunRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.RunID = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodeRobotServiceGetRunResponse 计算并一次写入当前方法响应载荷。
func encodeRobotServiceGetRunResponse(response *rpc.ResponseWriter, result1 RobotRunSnapshot) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1.RunID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureMessage)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1.RunID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := writer.WriteUint8(uint8(result1.State)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FinishedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.TargetUsers)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.ActiveRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.SucceededRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FailedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FlakyRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.Replacements)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureMessage)); err != nil {
		return err
	}
	return writer.Done()
}

// decodeRobotServiceGetRunResponse 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceGetRunResponse(data []byte) (result1 RobotRunSnapshot, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RunID = string(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RequestID = string(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.ScenarioName = string(decoded3)
	var decoded4 uint8
	decoded4, decodeErr = reader.ReadUint8()
	if decodeErr != nil {
		return
	}
	result1.State = RobotRunState(decoded4)
	var decoded5 int64
	decoded5, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedAtMS = int64(decoded5)
	var decoded6 int64
	decoded6, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FinishedAtMS = int64(decoded6)
	var decoded7 int64
	decoded7, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.TargetUsers = int64(decoded7)
	var decoded8 int64
	decoded8, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedRobots = int64(decoded8)
	var decoded9 int64
	decoded9, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.ActiveRobots = int64(decoded9)
	var decoded10 int64
	decoded10, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.SucceededRobots = int64(decoded10)
	var decoded11 int64
	decoded11, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FailedRobots = int64(decoded11)
	var decoded12 int64
	decoded12, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FlakyRobots = int64(decoded12)
	var decoded13 int64
	decoded13, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.Replacements = int64(decoded13)
	var decoded14 string
	decoded14, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureCode = string(decoded14)
	var decoded15 string
	decoded15, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureMessage = string(decoded15)
	decodeErr = reader.Done()
	return
}

// AwaitGetRun 以顺序编程外观等待 RPC 结果。
func (client RobotServiceClient) AwaitGetRun(ctx context.Context, arg1 GetRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, robotServiceGetRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceGetRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, robotServiceGetRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceGetRunResponse(data)
		return err
	})
	return
}

// CallGetRun 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client RobotServiceClient) CallGetRun(ctx context.Context, arg1 GetRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, robotServiceGetRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceGetRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, robotServiceGetRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceGetRunResponse(data)
		return err
	})
	return
}

// AsyncGetRun 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client RobotServiceClient) AsyncGetRun(ctx context.Context, arg1 GetRobotRunRequest, callback func(context.Context, RobotRunSnapshot, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, robotServiceGetRunMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeRobotServiceGetRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, robotServiceGetRunMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(RobotRunSnapshot), callErr)
			return
		}
		result1, decodeErr := decodeRobotServiceGetRunResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyGetRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) NotifyGetRun(ctx context.Context, arg1 GetRobotRunRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, robotServiceGetRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceGetRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, robotServiceGetRunMethodID, request)
}

// BroadcastGetRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) BroadcastGetRun(ctx context.Context, arg1 GetRobotRunRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, robotServiceGetRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceGetRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, robotServiceGetRunMethodID, request)
}

// encodeRobotServiceListScenariosRequest 计算并一次写入当前方法请求载荷。
func encodeRobotServiceListScenariosRequest(client rpc.Client, kind rpc.CallKind, arg1 ListRobotScenariosRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.Add(4); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteInt32(int32(arg1.Limit)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeRobotServiceListScenariosRequest 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceListScenariosRequest(data []byte) (arg1 ListRobotScenariosRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 int32
	decoded1, decodeErr = reader.ReadInt32()
	if decodeErr != nil {
		return
	}
	arg1.Limit = int32(decoded1)
	decodeErr = reader.Done()
	return
}

// encodeRobotServiceListScenariosResponse 计算并一次写入当前方法响应载荷。
func encodeRobotServiceListScenariosResponse(response *rpc.ResponseWriter, result1 ListRobotScenariosResponse) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddContainer(len(result1.Scenarios), result1.Scenarios == nil); err != nil {
		return err
	}
	for index1 := range result1.Scenarios {
		_ = index1
		if err := sizer.AddString(string(result1.Scenarios[index1].Name)); err != nil {
			return err
		}
		if err := sizer.Add(8); err != nil {
			return err
		}
		if err := sizer.Add(1); err != nil {
			return err
		}
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteContainer(len(result1.Scenarios), result1.Scenarios == nil); err != nil {
		return err
	}
	for index2 := range result1.Scenarios {
		if err := writer.WriteString(string(result1.Scenarios[index2].Name)); err != nil {
			return err
		}
		if err := writer.WriteInt64(int64(result1.Scenarios[index2].EntranceID)); err != nil {
			return err
		}
		if err := writer.WriteBool(bool(result1.Scenarios[index2].IsDefault)); err != nil {
			return err
		}
	}
	return writer.Done()
}

// decodeRobotServiceListScenariosResponse 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceListScenariosResponse(data []byte) (result1 ListRobotScenariosResponse, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var length1 int
	var isNil2 bool
	length1, isNil2, decodeErr = reader.ReadContainer()
	if decodeErr != nil {
		return
	}
	decodeErr = reader.CheckElements(length1, 13)
	if decodeErr != nil {
		return
	}
	if !isNil2 {
		result1.Scenarios = make([]RobotScenarioSummary, length1)
		for index3 := 0; index3 < length1; index3++ {
			var decoded4 string
			decoded4, decodeErr = reader.ReadString()
			if decodeErr != nil {
				return
			}
			result1.Scenarios[index3].Name = string(decoded4)
			var decoded5 int64
			decoded5, decodeErr = reader.ReadInt64()
			if decodeErr != nil {
				return
			}
			result1.Scenarios[index3].EntranceID = int64(decoded5)
			var decoded6 bool
			decoded6, decodeErr = reader.ReadBool()
			if decodeErr != nil {
				return
			}
			result1.Scenarios[index3].IsDefault = bool(decoded6)
		}
	}
	decodeErr = reader.Done()
	return
}

// AwaitListScenarios 以顺序编程外观等待 RPC 结果。
func (client RobotServiceClient) AwaitListScenarios(ctx context.Context, arg1 ListRobotScenariosRequest) (result1 ListRobotScenariosResponse, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, robotServiceListScenariosMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceListScenariosRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, robotServiceListScenariosMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceListScenariosResponse(data)
		return err
	})
	return
}

// CallListScenarios 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client RobotServiceClient) CallListScenarios(ctx context.Context, arg1 ListRobotScenariosRequest) (result1 ListRobotScenariosResponse, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, robotServiceListScenariosMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceListScenariosRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, robotServiceListScenariosMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceListScenariosResponse(data)
		return err
	})
	return
}

// AsyncListScenarios 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client RobotServiceClient) AsyncListScenarios(ctx context.Context, arg1 ListRobotScenariosRequest, callback func(context.Context, ListRobotScenariosResponse, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, robotServiceListScenariosMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeRobotServiceListScenariosRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, robotServiceListScenariosMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(ListRobotScenariosResponse), callErr)
			return
		}
		result1, decodeErr := decodeRobotServiceListScenariosResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyListScenarios 提交通知并主动放弃业务结果。
func (client RobotServiceClient) NotifyListScenarios(ctx context.Context, arg1 ListRobotScenariosRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, robotServiceListScenariosMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceListScenariosRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, robotServiceListScenariosMethodID, request)
}

// BroadcastListScenarios 提交通知并主动放弃业务结果。
func (client RobotServiceClient) BroadcastListScenarios(ctx context.Context, arg1 ListRobotScenariosRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, robotServiceListScenariosMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceListScenariosRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, robotServiceListScenariosMethodID, request)
}

// encodeRobotServiceStartRunRequest 计算并一次写入当前方法请求载荷。
func encodeRobotServiceStartRunRequest(client rpc.Client, kind rpc.CallKind, arg1 StartRobotRunRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.RequestID)); err != nil {
		return nil, err
	}
	if err := sizer.AddString(string(arg1.ScenarioName)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.RequestID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.WriteString(string(arg1.ScenarioName)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeRobotServiceStartRunRequest 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceStartRunRequest(data []byte) (arg1 StartRobotRunRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.RequestID = string(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.ScenarioName = string(decoded2)
	decodeErr = reader.Done()
	return
}

// encodeRobotServiceStartRunResponse 计算并一次写入当前方法响应载荷。
func encodeRobotServiceStartRunResponse(response *rpc.ResponseWriter, result1 RobotRunSnapshot) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1.RunID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureMessage)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1.RunID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := writer.WriteUint8(uint8(result1.State)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FinishedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.TargetUsers)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.ActiveRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.SucceededRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FailedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FlakyRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.Replacements)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureMessage)); err != nil {
		return err
	}
	return writer.Done()
}

// decodeRobotServiceStartRunResponse 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceStartRunResponse(data []byte) (result1 RobotRunSnapshot, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RunID = string(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RequestID = string(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.ScenarioName = string(decoded3)
	var decoded4 uint8
	decoded4, decodeErr = reader.ReadUint8()
	if decodeErr != nil {
		return
	}
	result1.State = RobotRunState(decoded4)
	var decoded5 int64
	decoded5, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedAtMS = int64(decoded5)
	var decoded6 int64
	decoded6, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FinishedAtMS = int64(decoded6)
	var decoded7 int64
	decoded7, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.TargetUsers = int64(decoded7)
	var decoded8 int64
	decoded8, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedRobots = int64(decoded8)
	var decoded9 int64
	decoded9, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.ActiveRobots = int64(decoded9)
	var decoded10 int64
	decoded10, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.SucceededRobots = int64(decoded10)
	var decoded11 int64
	decoded11, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FailedRobots = int64(decoded11)
	var decoded12 int64
	decoded12, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FlakyRobots = int64(decoded12)
	var decoded13 int64
	decoded13, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.Replacements = int64(decoded13)
	var decoded14 string
	decoded14, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureCode = string(decoded14)
	var decoded15 string
	decoded15, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureMessage = string(decoded15)
	decodeErr = reader.Done()
	return
}

// AwaitStartRun 以顺序编程外观等待 RPC 结果。
func (client RobotServiceClient) AwaitStartRun(ctx context.Context, arg1 StartRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, robotServiceStartRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceStartRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, robotServiceStartRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceStartRunResponse(data)
		return err
	})
	return
}

// CallStartRun 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client RobotServiceClient) CallStartRun(ctx context.Context, arg1 StartRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, robotServiceStartRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceStartRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, robotServiceStartRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceStartRunResponse(data)
		return err
	})
	return
}

// AsyncStartRun 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client RobotServiceClient) AsyncStartRun(ctx context.Context, arg1 StartRobotRunRequest, callback func(context.Context, RobotRunSnapshot, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, robotServiceStartRunMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeRobotServiceStartRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, robotServiceStartRunMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(RobotRunSnapshot), callErr)
			return
		}
		result1, decodeErr := decodeRobotServiceStartRunResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyStartRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) NotifyStartRun(ctx context.Context, arg1 StartRobotRunRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, robotServiceStartRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceStartRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, robotServiceStartRunMethodID, request)
}

// BroadcastStartRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) BroadcastStartRun(ctx context.Context, arg1 StartRobotRunRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, robotServiceStartRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceStartRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, robotServiceStartRunMethodID, request)
}

// encodeRobotServiceStopRunRequest 计算并一次写入当前方法请求载荷。
func encodeRobotServiceStopRunRequest(client rpc.Client, kind rpc.CallKind, arg1 StopRobotRunRequest) (*rpc.Buffer, error) {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(arg1.RunID)); err != nil {
		return nil, err
	}
	size, err := sizer.Size()
	if err != nil {
		return nil, err
	}
	buffer, err := client.AllocateRequest(size, kind)
	if err != nil {
		return nil, err
	}
	writer := rpc.NewWriter(buffer.Bytes())
	if err := writer.WriteString(string(arg1.RunID)); err != nil {
		buffer.Release()
		return nil, err
	}
	if err := writer.Done(); err != nil {
		buffer.Release()
		return nil, err
	}
	return buffer, nil
}

// decodeRobotServiceStopRunRequest 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceStopRunRequest(data []byte) (arg1 StopRobotRunRequest, decodeErr error) {
	reader := rpc.NewRequestReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	arg1.RunID = string(decoded1)
	decodeErr = reader.Done()
	return
}

// encodeRobotServiceStopRunResponse 计算并一次写入当前方法响应载荷。
func encodeRobotServiceStopRunResponse(response *rpc.ResponseWriter, result1 RobotRunSnapshot) error {
	sizer := rpc.NewSizer()
	if err := sizer.AddString(string(result1.RunID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := sizer.Add(1); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.Add(8); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := sizer.AddString(string(result1.FailureMessage)); err != nil {
		return err
	}
	size, err := sizer.Size()
	if err != nil {
		return err
	}
	target, err := response.Allocate(size)
	if err != nil {
		return err
	}
	writer := rpc.NewWriter(target)
	if err := writer.WriteString(string(result1.RunID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.RequestID)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.ScenarioName)); err != nil {
		return err
	}
	if err := writer.WriteUint8(uint8(result1.State)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FinishedAtMS)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.TargetUsers)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.StartedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.ActiveRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.SucceededRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FailedRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.FlakyRobots)); err != nil {
		return err
	}
	if err := writer.WriteInt64(int64(result1.Replacements)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureCode)); err != nil {
		return err
	}
	if err := writer.WriteString(string(result1.FailureMessage)); err != nil {
		return err
	}
	return writer.Done()
}

// decodeRobotServiceStopRunResponse 按固定契约顺序解码并校验完整载荷。
func decodeRobotServiceStopRunResponse(data []byte) (result1 RobotRunSnapshot, decodeErr error) {
	reader := rpc.NewResponseReader(data)
	var decoded1 string
	decoded1, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RunID = string(decoded1)
	var decoded2 string
	decoded2, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.RequestID = string(decoded2)
	var decoded3 string
	decoded3, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.ScenarioName = string(decoded3)
	var decoded4 uint8
	decoded4, decodeErr = reader.ReadUint8()
	if decodeErr != nil {
		return
	}
	result1.State = RobotRunState(decoded4)
	var decoded5 int64
	decoded5, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedAtMS = int64(decoded5)
	var decoded6 int64
	decoded6, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FinishedAtMS = int64(decoded6)
	var decoded7 int64
	decoded7, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.TargetUsers = int64(decoded7)
	var decoded8 int64
	decoded8, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.StartedRobots = int64(decoded8)
	var decoded9 int64
	decoded9, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.ActiveRobots = int64(decoded9)
	var decoded10 int64
	decoded10, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.SucceededRobots = int64(decoded10)
	var decoded11 int64
	decoded11, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FailedRobots = int64(decoded11)
	var decoded12 int64
	decoded12, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.FlakyRobots = int64(decoded12)
	var decoded13 int64
	decoded13, decodeErr = reader.ReadInt64()
	if decodeErr != nil {
		return
	}
	result1.Replacements = int64(decoded13)
	var decoded14 string
	decoded14, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureCode = string(decoded14)
	var decoded15 string
	decoded15, decodeErr = reader.ReadString()
	if decodeErr != nil {
		return
	}
	result1.FailureMessage = string(decoded15)
	decodeErr = reader.Done()
	return
}

// AwaitStopRun 以顺序编程外观等待 RPC 结果。
func (client RobotServiceClient) AwaitStopRun(ctx context.Context, arg1 StopRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareAwait(ctx, robotServiceStopRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceStopRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Await(ctx, robotServiceStopRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceStopRunResponse(data)
		return err
	})
	return
}

// CallStopRun 在当前普通 goroutine 中阻塞并返回 RPC 结果。
func (client RobotServiceClient) CallStopRun(ctx context.Context, arg1 StopRobotRunRequest) (result1 RobotRunSnapshot, err error) {
	preparedClient, err := client.client.PrepareCall(ctx, robotServiceStopRunMethodID)
	if err != nil {
		return
	}
	defer preparedClient.FinishInvocation()
	request, err := encodeRobotServiceStopRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return
	}
	err = preparedClient.Call(ctx, robotServiceStopRunMethodID, request, func(data []byte) error {
		result1, err = decodeRobotServiceStopRunResponse(data)
		return err
	})
	return
}

// AsyncStopRun 提交请求，并在 owner 的后续串行任务中执行一次回调。
func (client RobotServiceClient) AsyncStopRun(ctx context.Context, arg1 StopRobotRunRequest, callback func(context.Context, RobotRunSnapshot, error)) error {
	if callback == nil {
		return errs.ErrInvalidArgument
	}
	preparedClient, err := client.client.PrepareAsync(ctx, robotServiceStopRunMethodID)
	if err != nil {
		return err
	}
	handedOff := false
	defer func() {
		if !handedOff {
			preparedClient.FinishInvocation()
		}
	}()
	request, err := encodeRobotServiceStopRunRequest(preparedClient, rpc.CallRequest, arg1)
	if err != nil {
		return err
	}
	handedOff = true
	return preparedClient.Async(ctx, robotServiceStopRunMethodID, request, func(callbackCtx context.Context, data []byte, callErr error) {
		if callErr != nil {
			callback(callbackCtx, *new(RobotRunSnapshot), callErr)
			return
		}
		result1, decodeErr := decodeRobotServiceStopRunResponse(data)
		callback(callbackCtx, result1, decodeErr)
	})
}

// NotifyStopRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) NotifyStopRun(ctx context.Context, arg1 StopRobotRunRequest) error {
	preparedClient, err := client.client.PrepareNotify(ctx, robotServiceStopRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceStopRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Notify(ctx, robotServiceStopRunMethodID, request)
}

// BroadcastStopRun 提交通知并主动放弃业务结果。
func (client RobotServiceClient) BroadcastStopRun(ctx context.Context, arg1 StopRobotRunRequest) error {
	preparedClient, err := client.client.PrepareBroadcast(ctx, robotServiceStopRunMethodID)
	if err != nil {
		return err
	}
	request, err := encodeRobotServiceStopRunRequest(preparedClient, rpc.CallNotify, arg1)
	if err != nil {
		return err
	}
	return preparedClient.Broadcast(ctx, robotServiceStopRunMethodID, request)
}

// robotServiceDispatcher 把 MethodID 静态分派到 RobotService 实现。
type robotServiceDispatcher struct{ impl RobotService }

// NewRobotServiceDispatcher 创建不使用反射的静态 Dispatcher。
func NewRobotServiceDispatcher(impl RobotService) rpc.Dispatcher {
	return &robotServiceDispatcher{impl: impl}
}

// ContractID 返回生成期冻结的契约标识。
func (dispatcher *robotServiceDispatcher) ContractID() rpc.ContractID { return robotServiceContractID }

// Fingerprint 返回生成期冻结的完整 Schema 指纹。
func (dispatcher *robotServiceDispatcher) Fingerprint() rpc.ContractFingerprint {
	return robotServiceFingerprint
}

// Dispatch 解码请求、调用业务实现并按调用类型决定是否编码响应。
func (dispatcher *robotServiceDispatcher) Dispatch(ctx context.Context, methodID rpc.MethodID, kind rpc.CallKind, request []byte, response rpc.ResponseWriter) (rpc.ResponseWriter, error) {
	switch methodID {
	case robotServiceGetRunMethodID:
		arg1, err := decodeRobotServiceGetRunRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.GetRun(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.GetRun(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeRobotServiceGetRunResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case robotServiceListScenariosMethodID:
		arg1, err := decodeRobotServiceListScenariosRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.ListScenarios(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.ListScenarios(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeRobotServiceListScenariosResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case robotServiceStartRunMethodID:
		arg1, err := decodeRobotServiceStartRunRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.StartRun(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.StartRun(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeRobotServiceStartRunResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	case robotServiceStopRunMethodID:
		arg1, err := decodeRobotServiceStopRunRequest(request)
		if err != nil {
			return response, err
		}
		if kind == rpc.CallNotify {
			_, callErr := dispatcher.impl.StopRun(ctx, arg1)
			if callErr != nil {
				return response, callErr
			}
			return response, nil
		}
		if kind != rpc.CallRequest {
			return response, errs.ErrInvalidArgument
		}
		result1, callErr := dispatcher.impl.StopRun(ctx, arg1)
		if callErr != nil {
			return response, callErr
		}
		if err := encodeRobotServiceStopRunResponse(&response, result1); err != nil {
			return response, err
		}
		return response, nil
	default:
		return response, errs.ErrRPCMethodNotFound
	}
}

func init() {
	rpc.RegisterGeneratedContract(rpc.GeneratedContractDescriptor{
		ServiceName:  "RobotService",
		ContractName: "origingame/protocol/rpc.RobotService",
		ContractID:   robotServiceContractID,
		Fingerprint:  robotServiceFingerprint,
		NewDispatcher: func(implementation any) (rpc.Dispatcher, bool) {
			target, ok := implementation.(RobotService)
			if !ok {
				return nil, false
			}
			return NewRobotServiceDispatcher(target), true
		},
	})
}
