
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package tabledef;

const (
    /**
     * 血量
     */
    AttrType_HP = 1;
    /**
     * 蓝量
     */
    AttrType_MP = 2;
    /**
     * 速度
     */
    AttrType_Speed = 3;
)

